### ISSUE TITLE
Change Name of Repo to "cityasacampus"

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#103]

**Comment by chadwhitacre** [comment]
Done.

**Comment by MatthewVita** [comment]
we broke http://cityasacampus.org/ :O

**Comment by MatthewVita** [comment]
didn't break our CI though (https://codeship.com/projects/69801/builds/7678386) :D

**Comment by chadwhitacre** [comment]
I just pushed a commit to see if that will get GH Pages back on track: https://github.com/saxifrage/cityasacampus/commit/46d3d7a0e2a24a2c893a57958da6d5cec6cc6cd9.

**Comment by chadwhitacre** [comment]
Huzzah! :dancer:
