### ISSUE TITLE
Establish Topics Config on Backend

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#109]
instead of putting the topics in the frontend config file, let's store them on the backend since we already have an endpoint.

To keep things simple, we'll just have them stored in a config file w/ Rails, but the user will eventually have a fully working admin dashboard where they can CRUD topics with database persistence :)

**Comment by justinxreese** [comment]
:+1:

**Comment by MatthewVita** [comment]
@justinxreese what do you think of:

``` ruby
class Topic < ActiveRecord::Base
  def self.read_from_temp_config
    return Rails.application.config.topics
  end
end
```

where the config is in `application.rb` with something basic like:

``` ruby
config.topics = [{
  :name => 'history'
}, {
  :name => 'math'
}]
```

**Comment by justinxreese** [comment]
Topic should just not be an ActiveRecord model and return a hash of topics in an `all` method

**Comment by MatthewVita** [comment]
@justinxreese okay, I'll remove the ActiveRecord inheritance, change the method name to all, adjust the controller accordingly, and send you a PR sometime in the coming days.

**Comment by MatthewVita** [comment]
@justinxreese our CI is failing with my branch for this work and I would appreciate your input:

https://github.com/saxifrage/learn/commit/534042f986765bb72351d937ecadcf76f3b9d1dc

...errors look like this:

```
1) Error:
OpportunityInstancesControllerTest#test_should_show_opportunity_instance:
ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "created_at" violates not-null constraint
DETAIL:  Failing row contains (1, MyString, MyString, MyString, null, null).
: INSERT INTO "topics" ("name", "short_name", "child_of_topic") VALUES ('MyString', 'MyString', 'MyString')


Error:
OpportunityInstancesControllerTest#test_should_show_opportunity_instance:
NoMethodError:  method `each' for nil:NilClass
```

...I don't remember seeing these db errors until I removed the ActiveRecord inheritance.

**Comment by justinxreese** [comment]
Left some minor notes (style, not causing this error) from my phone but
need more context to fully diagnose. Did you add the Topic model, I forget?

**Comment by MatthewVita** [comment]
@justinxreese thanks for the notes. I just --amend'ed my changes.

The Topic model already exists in `/models/topic.rb`, I just slimmed it down to the one `all` method and removed the ActiveRecord inheritance.

**Comment by justinxreese** [comment]
Ok. The error is being caused by the fact that it already existed as a
database model. I can add a commit tomorrow that'll fix it. We should
probably switch to a class method rather than deleting the DB tables.
Actually typing this out makes me realize the seeds use topics. I'll take a
look at this soon.

**Comment by MatthewVita** [comment]
@justinxreese my goal was to just add in this `all` method (well, and remove any other unused model methods) because I know some other areas in the db reference `topic`, but it's either keep the ActiveRecord model and add in `all` or ditch ActiveRecord and remove all db refs to it.

Anyways, I committed in the ActiveRecord inheritance and all is well :+1: (we'll eventually go back to the ActiveRecord approach post-MVP anyways):
https://codeship.com/projects/69801/builds/5711828

...if I send you a PR, should I include the `client` branch stuff I based my `topics` branch on, despite it breaking things with our build since we don't have the `gulp` hooks in yet?

**Comment by justinxreese** [comment]
So I'm getting into this and realizing, if topics aren't persisted, they aren't going to have an ID and thus nothing can be associated with them. I think we need to go all the way and actually implement topics as saved instances, whether they are managed by a CRUD interface or not. Thoughts @MatthewVita?

**Comment by MatthewVita** [comment]
@justinxreese so the concern is that opportunity_instances will be created without an actual relationship to a topic, causing us pain when we move topics to ActiveRecord?

If I'm understanding this correctly and we follow the path we've been currently considering, it sounds like each city will have to run some sort of custom migration later on?

**Comment by MatthewVita** [comment]
actually, looks we'll need the topics in ActiveRecord now so we can do the opportunity instances search against `name` and joined `topics`... right?
