### ISSUE TITLE
Explore Page - Real Calls

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#114]
@matthewvita and @justinxreese to work on getting RoR and Angular ready for the Opportunity page.

Frontend: 
- adjust endpoint reference as needed
- adjust conventions as needed (right now I'm using `opportunities` instead of `opportunity_instances`)

Backend:
- finalize get endpoint

**Comment by MatthewVita** [comment]
@justinxreese just a quick dump for you to consider:

routes.rb:

``` ruby
resources :opportunity_instances do
  collection do
    get 'topics/:title', action: :topic
    get 'search/:term', action: :search
  end
end
```

...with the ActiveRecord query resolving to something like this (note there is no search as correlated to topics until we work that out and I commented out the last condition since it just didn't work for me... perhaps we should have `hide` default to false):

``` sql
SELECT 
  o.*
FROM 
  opportunity_instances o
WHERE
  LOWER(o.name) LIKE '%software%'
AND
  o.ends_at < CURRENT_TIMESTAMP
/*
AND
  o.hide = FALSE;
*/
```

**Comment by MatthewVita** [comment]
...actually, here's the AR query:

``` ruby
# GET /opportunity_instances/search/:term.json
def search
  paginate json: OpportunityInstance
    .where(["name ILIKE ?", "%#{params[:term]}%"])
    .where("ends_at < CURRENT_TIMESTAMP")
    .as_json
end
```

... http://localhost:3000/opportunity_instances/search/software.json?page=1 works :)

anyway to rid of the `.as_json` call?

**Comment by justinxreese** [comment]
We can't take parameters from a URL and directly inject them to SQL. It's dangerous and also non-performant. We should use a search indexing engine https://github.com/sunspot/sunspot

**Comment by MatthewVita** [comment]
I actually think the parameterization mechanism in AR protects us from injection?

sunspot looks cool for full-text... do you think we should include it now or post MVP?

also, for the other search endpoint, I was thinking something like (trivial example) since you mentioned you wanted the 2 search endpoints separate:

``` sql
SELECT
  o.*
FROM
  opportunity_instances o
JOIN
  topics t
ON
  t.id = o.topic_id
WHERE
  t.name ILIKE '%software%'
AND
  o.ends_at < CURRENT_TIMESTAMP;
```

**Comment by justinxreese** [comment]
The topic endpoint wouldn't be a search. It's tied to an ID since those are
known.

**Comment by justinxreese** [comment]
You are right that AR will protect us. It's still just not great practice.

The only thing holding me back from saying we should absolutely use sunspot right now is the fact that we want to be able to clone copies of the app across other places and that's another piece of setup. Can it be automated? IDK

**Comment by justinxreese** [comment]
Maybe take advantage of postgres full text search? But I really don't like that this option would tie us to one possible database

https://github.com/Casecommons/pg_search
https://github.com/textacular/textacular

**Comment by justinxreese** [comment]
Textacular is the decision from @MatthewVita and I's conversation

**Comment by justinxreese** [comment]
We'll also add categories to full text search

**Comment by justinxreese** [comment]
``` json
{"topics":[{"id":1,"name":"Software","short_name":null,"child_of_topic":null},  {"id":2,"name":"Software","short_name":null,"child_of_topic":null},  {"id":3,"name":"Software","short_name":null,"child_of_topic":null}]}
```

**Comment by MatthewVita** [comment]
closing b/c of https://github.com/saxifrage/learn/issues/118
