### ISSUE TITLE
Implement Full-text Search module with Name & Topic

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#118]
https://github.com/textacular/textacular

**Comment by MatthewVita** [comment]
@justinxreese here's the result of my playing around with Textacular and studying up on PG's full text search capabilities in general. Everything is in the `full-text-search` branch. I ask you to review my code and comment on anything concerning about the following demo:

```
UPDATE
  opportunity_instances
SET
  description = 'this is a test'
WHERE
  id = 3;
```

```
UPDATE
  opportunity_instances
SET
  description = 'this is a test'
WHERE
  id = 4;
```

```
UPDATE
  topics
SET
  name = 'foobar'
WHERE
  id = 1;
```

---

when searching against 'software':
![1](https://cloud.githubusercontent.com/assets/1715206/8510388/a340f6a0-22ad-11e5-9ff6-5ae83b07c72f.PNG)

when searching against 'softwae' [0]:
![2](https://cloud.githubusercontent.com/assets/1715206/8510389/a64971ba-22ad-11e5-87d4-0d4d278db503.PNG)

when searching against 'foobar':
![3](https://cloud.githubusercontent.com/assets/1715206/8510390/a8a5fdca-22ad-11e5-9180-e0c267925aa5.PNG)

when searching against 'this is a test':
![4](https://cloud.githubusercontent.com/assets/1715206/8510391/ab63ff1c-22ad-11e5-91ae-fa5b6b841041.PNG)

when searching against 'ths is a tst :)' [1]:
![5](https://cloud.githubusercontent.com/assets/1715206/8510392/addb8a3a-22ad-11e5-8caf-d257b199dcf1.PNG)

[0] I don't know why this isn't returning the same resultset as the search against 'software'
[1] I find it very cool that this just works :)

**Comment by justinxreese** [comment]
Maybe open it as a PR so I can quickly see the diff? I'll let you know if I see anything. textacular looks like it may work out of the box awesomely. We may need to configure heroku to support the full text search add-on in postgres. not sure it's there by default

**Comment by MatthewVita** [comment]
https://github.com/saxifrage/learn/pull/142 - Thanks!

As for Textacular working out of the box and configuration... that's pretty much the case. The only thing that we have to pay attention to is the `CREATE EXTENSION IF NOT EXISTS pg_trgm;` part of the migration I added... as long as the Heroku user has the correct PG privileges (superuser?), we'll be fine.
