### ISSUE TITLE
Make Lazy Loader Use New Convention

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#125]

**Comment by MatthewVita** [comment]
done: https://github.com/saxifrage/learn/commit/a5dd84871e61ff7b66b2b9cb742f303e82d33a31

example (also hides button when the end of paging is recognized):

![dev pittsburgh city as a campus explore](https://cloud.githubusercontent.com/assets/1715206/8400180/2f903dd4-1de8-11e5-808f-727932a44902.png)
![dev pittsburgh city as a campus explore2](https://cloud.githubusercontent.com/assets/1715206/8400181/2fa0782a-1de8-11e5-9a24-f8ffc397805b.png)

@timothyfcook do we have a better image or HTML/CSS for the "See More..." button and the loading indicator gif?

**Comment by timothyfcook** [comment]
@MatthewVita not yet! I'll find something a la #139
