### ISSUE TITLE
Create dynamic learning resource map

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#131]
Been working on these concepts for a while. It's time to build it.

For our initial prototype, we'll start with a template that has manually inputted data. Eventually we'll want it to generate visualizations dynamically from the database based on topical relationships, etc.

We'll use this for City of Learning this year, as well as long-term in the CaaC work.

Mozilla built a poorly designed page that starts to get at the idea of "Learning Pathways" and visualizing the connections between content: http://discover.openbadges.org/

In a lot of the whitepapers and blog posts I've seen that reference the importance of this type of visualization, a lot of people reference video game skill trees, especially this one: https://d3rants.files.wordpress.com/2012/08/path-of-exile-passive-tree.png

For specific technology, I'm thinking D3 makes sense. 

In order to build this, I was pondering a trifecta of @chelseaerdner (to make it look good), @cameronscott137 (to implement the design) and @whit537 (to help with the data and technical implementation).

For D3 vizualization inspiration, I think these are good:
1. Force Layouts (networks with nodes/lines)
   - http://bl.ocks.org/couchand/6420534
   - http://bl.ocks.org/mbostock/1062288
   - http://bl.ocks.org/mbostock/1093130
   - http://www.redotheweb.com/CodeFlower/
2. Hexagonal Grids
   - The [hexagonal grid](http://d3js.org/) on the D3 website
   - An [interactive](http://bl.ocks.org/mbostock/5249328) hex grid
   - Hex grid [resources](http://www.redblobgames.com/grids/hexagons/)
   - Self-organizing [heat map](http://www.visualcinnamon.com/2013/07/self-organizing-maps-creating-hexagonal.html) hex grids.
3. Knowledge Cartography
   - Knowledge [maps](http://www.knowledgecartography.org/)

**Comment by MatthewVita** [comment]
This can be closed, yes? Another user story can be made to address the integration piece, I suppose.

**Comment by timothyfcook** [comment]
Yeah! It's nearly finished: http://cityasacampus.org/map/
