### ISSUE TITLE
gulp freezes

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#137]
![screen shot 2015-06-24 at 9 15 25 am](https://cloud.githubusercontent.com/assets/1823300/8331120/7f18da60-1a54-11e5-9953-00ca99a95b6a.png)

**Comment by timothyfcook** [comment]
stuck here.

**Comment by MatthewVita** [comment]
@timothyfcook it's not actually stuck... it's just listening for file changes (development mode). You are free to open another tab and `cd ../ && rails s` or simple `ctrl + c` once Gulp says `default` is finished.

also, you can use `gulp production` if you really want gulp to exit once done (this is for production mode for heroku)

**Comment by MatthewVita** [comment]
@timothyfcook can we close this?
