### ISSUE TITLE
Put CaaC on the internet at learnpgh.org

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#144]
Once we finish fully implementing the design for the Opportunity pages and Explore, I'd be interested in putting it up online at learnpgh.org with some dummy content.

I'm having a lot of conversations with people about the project and it would be nice to have something to reference.

Then, when the Admin account side is ready to go we can hit the ground running.

We can also host the beautiful Learning Resource Maps as well. @whit537 and I have finished an initial [prototype](https://github.com/saxifrage/caac-map) that is ready for the web.

**Comment by MatthewVita** [comment]
closing because I created an Epic for this:: https://github.com/saxifrage/cityasacampus/milestones/CaaC%20Deployment%20Epic
