### ISSUE TITLE
Use CNAMEs to access organizations by subdomain

### ISSUE THREAD

**Issue by justinxreese** [saxifrage/learn#15]
Docs on how to do it: http://www.davesouth.org/blog/rails/rails-subdomains-cnames-and-crzy-me

**Comment by justinxreese** [comment]
Milestone 2/3'ish

**Comment by chadwhitacre** [comment]
https://www.google.com/search?q=rails+subdomain+routing

http://asciicasts.com/episodes/221-subdomains-in-rails-3
http://guides.rubyonrails.org/routing.html
http://stackoverflow.com/questions/21536986/rails-routes-url-and-subdomains
http://www.raysrashmi.com/2014/07/23/rails-routes-constraints
http://richonrails.com/articles/basic-subdomains-in-ruby-on-rails
https://gist.github.com/bsodmike/1369419

**Comment by chadwhitacre** [comment]
Done for today. At this point I'm planning to pick up with this again next Friday morning. I won't be down here at the office but I should be able to get a few hours in early before our 10:00 call. The Friday after that I'm out completely, so I'll see what I can squeeze in that week.

**Comment by timothyfcook** [comment]
welcome back!

**Comment by chadwhitacre** [comment]
:-)

**Comment by chadwhitacre** [comment]
Alright, so I've got my dev environment all ready (#57). What's my target here?

STREAM OF CONSCIOUSNESS GO!!!!!!!!!!!!!!!!!! :racehorse:

**Comment by chadwhitacre** [comment]
http://www.davesouth.org/blog/rails/rails-subdomains-cnames-and-crzy-me

**Comment by chadwhitacre** [comment]
I'm trying to get [vcap.me](https://github.com/cloudfoundry-attic/vcap) to work. It's supposed to route to localhost to aid with development in subdomain/CNAME kind of situations.

**Comment by chadwhitacre** [comment]
vcap.me indeed resolves to 127.0.0.1:

```
$ dig vcap.me

; <<>> DiG 9.8.3-P1 <<>> vcap.me
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34334
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;vcap.me.                       IN      A

;; ANSWER SECTION:
vcap.me.                3600    IN      A       127.0.0.1

;; Query time: 341 msec
;; SERVER: 75.75.76.76#53(75.75.76.76)
;; WHEN: Fri Apr  3 09:09:37 2015
;; MSG SIZE  rcvd: 41

$
```

**Comment by chadwhitacre** [comment]
However:

http://localhost:3000/ ← fine
http://127.0.0.1:3000/ ← not fine

**Comment by chadwhitacre** [comment]
``` shell
$ bin/rails s -b0.0.0.0
```

Yay!

**Comment by chadwhitacre** [comment]
Okay! Now to route something differently based on `Host` ...

![screen shot 2015-04-03 at 9 13 07 am](https://cloud.githubusercontent.com/assets/134455/6982597/b79395c8-d9e1-11e4-8a73-7cf5eda0472b.png)

**Comment by timothyfcook** [comment]
The goal here is: Once Organizers have their own page on which their events are listed (e.g. http://national.cityoflearning.me/organization-details?id=30) we want them to be able to create a CNAME page on their own domain that has that page on it. They should be able to set this up in the Organizer dashboard when they log in.

**Comment by chadwhitacre** [comment]
http://guides.rubyonrails.org/routing.html#request-based-constraints

**Comment by chadwhitacre** [comment]
I'm not sure yet that I want to route things differently. At this point I want to simply vary something based on the `Host`. Rather than focusing on `routes.rb` right now I'm going to try to get the `Host` header to display on the page.

**Comment by chadwhitacre** [comment]
O.O

![screen shot 2015-04-03 at 9 30 16 am](https://cloud.githubusercontent.com/assets/134455/6982767/10487b5a-d9e4-11e4-9aca-d3a88f47d3dd.png)

**Comment by chadwhitacre** [comment]
I've figured out how to change HTML on the site. :)

![screen shot 2015-04-03 at 9 31 09 am](https://cloud.githubusercontent.com/assets/134455/6982778/2f9cbe12-d9e4-11e4-8d6c-7a96df0b0dcd.png)

**Comment by chadwhitacre** [comment]
Blam.

![screen shot 2015-04-03 at 9 44 44 am](https://cloud.githubusercontent.com/assets/134455/6982947/181e2580-d9e6-11e4-895b-054741ae07fa.png)

**Comment by chadwhitacre** [comment]
All right! So now to filter [`@opportunities`](https://github.com/saxifrage/learn/blob/f6144b1eb19bdcf4524c6aa9c4ba0050405a7c2f/app/controllers/application_controller.rb#L7) based on `Host`.

**Comment by chadwhitacre** [comment]
http://guides.rubyonrails.org/active_record_querying.html#conditions

**Comment by chadwhitacre** [comment]
PR started in #74.
