### ISSUE TITLE
Add Venue Name

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#152]
add venue name per https://github.com/saxifrage/learn/blob/master/examples/opportunity_instance_linked_data.json#L30

**Comment by Tim-Stimach** [comment]
Gonna git it dun

**Comment by MatthewVita** [comment]
closing. we had the venue_name. all we needed was to add some seed data: https://github.com/saxifrage/learn/commit/e885024fa9a69f985e92317b86f624f87b3a96dc
