### ISSUE TITLE
Free Code Camp

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#158]
http://www.freecodecamp.com/ is a place to "learn to code by building projects for nonprofits". I think we should register City as a Campus x Saxifrage up for this. I'll be the owner of making sure the volunteers have tasks and know what the scope of their work is.

Thoughts?

**Comment by MatthewVita** [comment]
btw http://www.freecodecamp.com/field-guide/if-free-code-camp-is-free-how-does-it-make-money

**Comment by timothyfcook** [comment]
@MatthewVita sounds fine to me if you think there is some work you can give them to do.

I could see starting to build out some of the basic landing pages; we also talked about building pages for Topic areas in #52 

I can help come up with tasks if you're up for owning their involvement. 

Cool!

**Comment by timothyfcook** [comment]
Hmmm... upon further investigation, it looks like they are better suited to more traditional non-profit operations who need tech help, not tech projects that are non-profit. According to their survey, sounds like we are not a good fit.

**Comment by MatthewVita** [comment]
thanks for reading the fine print
