### ISSUE TITLE
Responsive UI Issues

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#160]
@cameronscott137 3 things I'd like to work out with you, when you get a chance:
1. our footer doesn't stick to the bottom
2. a while back, I quickly threw the explore cards on the page with floats/margin tricks to make them be in a "grid". We should probably use https://github.com/saxifrage/learn/tree/master/client/app/shared/grid instead (I think this is the system from Bootstrap?)
3. our navbar doesn't look good when on a phone. We'll need to use some media queries there

will you be free at some point this or next week to pair on this with me? I've been into Einstein Bros lately... my treat.

**Comment by cameronscott137** [comment]
@MatthewVita Totally. Let me look at each of the issues above, and we can get together sometime later this week.

**Comment by MatthewVita** [comment]
cool, LMK.

**Comment by timothyfcook** [comment]
Maybe I'll join yinz, keep me posted!

**Comment by MatthewVita** [comment]
you just want the free bagels

**Comment by timothyfcook** [comment]
Duh

**Comment by MatthewVita** [comment]
@cameronscott137, @timothyfcook can you guys meet 5pm on Wednesday? 

Einstein Bros Bagels
436 Seventh Ave, Pittsburgh, PA 15219

**Comment by timothyfcook** [comment]
Good with me.

I'll meet anywhere anytime!

**Comment by MatthewVita** [comment]
@timothyfcook glad you're able to make it.

@cameronscott137 can you confirm you'll be able to make it?

**Comment by MatthewVita** [comment]
@cameronscott137 are you able to make it tomorrow?

**Comment by timothyfcook** [comment]
Heard a rumor that he is on vacation!

**Comment by MatthewVita** [comment]
Okay. Let's try for when he's back

**Comment by MatthewVita** [comment]
@timothyfcook, @cameronscott137: can we try for this Wednesday? :)

**Comment by timothyfcook** [comment]
I'm down. Not sure if @cameronscott137 is back in the country yet... ?

**Comment by cameronscott137** [comment]
I am stateside and available tomorrow. Still want to do 5PM at Einstein?

On Tue, Sep 1, 2015 at 2:54 PM, Tim Cook notifications@github.com wrote:

> I'm down. Not sure if @cameronscott137
> https://github.com/cameronscott137 is back in the country yet... ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/cityasacampus/issues/160#issuecomment-136826993
> .

## 

Cameron
(610) 883-7342

**Comment by timothyfcook** [comment]
Unfortunately I have a Sprout Fund board meeting at 5:45. I could meet until then if we met closer to the Sprout office or yinz can meet w/o me. I'm not that helpful anyways : )

**Comment by MatthewVita** [comment]
@cameronscott137 awesome, let's do 5pm at Einstein.

**Comment by cameronscott137** [comment]
@matthewvita, any chance you have the flexibility to meet closer to the
East End? I'm gonna be coming in hot from a meeting that ends at 4:45, and
don't wanna keep you waiting if things run over.

On Tue, Sep 1, 2015 at 6:44 PM, Matthew Vita notifications@github.com
wrote:

> @cameronscott137 https://github.com/cameronscott137 awesome, let's do
> 5pm at Einstein.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/cityasacampus/issues/160#issuecomment-136883960
> .

## 

Cameron
(610) 883-7342

**Comment by timothyfcook** [comment]
I might be able to join as well, keep me posted on your plans!

**Comment by MatthewVita** [comment]
Sure where at?

**Comment by cameronscott137** [comment]
Mind doing Zeke's (6015 Penn Ave, Pittsburgh, PA 15206) in the East
Liberty? Is that too far out of your way?

On Wed, Sep 2, 2015 at 4:35 PM, Matthew Vita notifications@github.com
wrote:

> Sure where at?
> 
> On Wed, Sep 2, 2015, 3:37 PM Tim Cook notifications@github.com wrote:
> 
> > I might be able to join as well, keep me posted on your plans!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/saxifrage/cityasacampus/issues/160#issuecomment-137222733
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/cityasacampus/issues/160#issuecomment-137236907
> .

## 

Cameron
(610) 883-7342

**Comment by cameronscott137** [comment]
We're confirmed for Zekes's at 5ish if you can join us, Tim?

On Wednesday, September 2, 2015, Cameron Scott cameron.scott137@gmail.com
wrote:

> Mind doing Zeke's (6015 Penn Ave, Pittsburgh, PA 15206) in the East
> Liberty? Is that too far out of your way?
> 
> On Wed, Sep 2, 2015 at 4:35 PM, Matthew Vita <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Sure where at?
> > 
> > On Wed, Sep 2, 2015, 3:37 PM Tim Cook <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > > I might be able to join as well, keep me posted on your plans!
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/saxifrage/cityasacampus/issues/160#issuecomment-137222733
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/saxifrage/cityasacampus/issues/160#issuecomment-137236907
> > .
> 
> ## 
> 
> Cameron
> (610) 883-7342

## 

Cameron
(610) 883-7342

**Comment by timothyfcook** [comment]
I think so! See yinz there. Let me buy all of the treats.

**Comment by MatthewVita** [comment]
Currently enjoying an artisan chocolate bar and good wifi.

**Comment by chadwhitacre** [comment]
!m *

**Comment by cameronscott137** [comment]
#### Our footer doesn't stick to the bottom

 This is a CSS solution involving negative margins. I'll take that.

**Comment by cameronscott137** [comment]
#### Grid
- Responsive `masonry.js` for the cards.
- Gonna ditch the CSS-governed circular icons for right now; will clean up square icons, round the edges, etc.

**Comment by cameronscott137** [comment]
#### Nav

On smaller screen sizes, will prioritize search, and collapse everything else off-canvas.

**Comment by MatthewVita** [comment]
reassigned to @cameronscott137 because design stuff

**Comment by cameronscott137** [comment]
Re: nav

![screen shot 2015-09-22 at 12 31 26 pm](https://cloud.githubusercontent.com/assets/2473472/10024580/ee0323c8-6125-11e5-9ea9-4eb01dc153fa.png)

Up on the `bourbon` branch. Prepping for off-canvas to the right.

**Comment by cameronscott137** [comment]
In addition, I've migrated off the Bootstrap grid to [Neat](http://neat.bourbon.io/), a sass grid that lives on top of [Bourbon](http://bourbon.io/). Neat is lighter weight and more sassy; Bourbon provides us with a ton of handy outta-the-box mixins to keep styles clean.

You may notice a few things breaking on the `bourbon` branch for the next day or so as I finish up the migration.

**Comment by timothyfcook** [comment]
@cameronscott137 can we close this ticket?

I'm still seeing some funny activity, like:
- inconsistent columns
- excess right-margins and non-centered columns

Screenshots below:
![screen shot 2015-10-08 at 10 13 29 am](https://cloud.githubusercontent.com/assets/1823300/10368850/5706a4fe-6da5-11e5-9309-a3b40c97c127.png)
![screen shot 2015-10-08 at 10 13 23 am](https://cloud.githubusercontent.com/assets/1823300/10368851/570962ac-6da5-11e5-9910-510dc5e12682.png)

**Comment by MatthewVita** [comment]
@timothyfcook I believe he's working in a branch and is not in master. @cameronscott137 do you need any help with finishing this work off?
