### ISSUE TITLE
Add `difficulty` and `duration` to data model

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#161]
Per the conversation in #93 I think it makes sense to add some new data types to match with what we're exploring with the cityasacampus.org/map ...specifically:
- `difficulty` as an integer (data validation: "1,2,3") 1 = Beginner, 2 = Intermediate, 3 = Expert
- `duration` as a number of minutes (provides us with the total scope of the resource, so that users can sort based on roughly how long it will take them to complete a certain resource. In the [map](cityasacampus.org/map) the longer the duration, the bigger the size of the resource brick.

**Comment by justinxreese** [comment]
Is the map using opportunity_instances?

**Comment by MatthewVita** [comment]
@justinxreese https://github.com/saxifrage/caac-map/blob/master/output/resources.json (the data lives in google spreadsheets)

**Comment by timothyfcook** [comment]
Eventually, we should reconcile the two data models. We built this one separately so that we could specifically consider what properties would be significant for the maps. It's been a good exercise and, I think, will result in a stronger final data model for the opportunities/instances.

In the final version, it might actually make sense for the resources in the maps to be `opportunity` so that they don't expire like an `opportunity_instance`.
