### ISSUE TITLE
Revise Roadmap

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#164]
It's out of date!

http://cityasacampus.org/doc/roadmap.html

**Comment by MatthewVita** [comment]
2 cents: keep it broad/flexible because we lean more towards Agile than Waterfall.

**Comment by MatthewVita** [comment]
@timothyfcook I was thinking it would be cool to break up the roadmap by subproject roadmaps, since we have the platform itself, maps, and universal badge API projects going on at the same time (in theory, they will all merge later on).

**Comment by timothyfcook** [comment]
Sounds wise to me. Thanks!

**Comment by timothyfcook** [comment]
Cleaned up the current roadmap. Later we can spec out specific work for the badge API and maybe the ongoing maps work. Although the maps work is defined pretty clearly in its own repo.

**Comment by MatthewVita** [comment]
:tada:
