### ISSUE TITLE
admin area

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#165]
@justinxreese can you prefix the admin area routes with `/admin`?

example: `/opportunities/new` would be `/admin/opportunities/new`

**Comment by timothyfcook** [comment]
Nice. Then admin users can login at e.g. `learnpgh.com/admin`

**Comment by timothyfcook** [comment]
Meeting here with @cameronscott137 and @MatthewVita ...looks like we need this to move forward on some priorities. @justinxreese can you execute?

**Comment by justinxreese** [comment]
There's already an open pull request for this

**Comment by timothyfcook** [comment]
Got it. Thanks!

**Comment by MatthewVita** [comment]
@justinxreese, @timothyfcook I just merged the PR into master. I'm happy with the code, however we can't close this issue quite yet. While the `admin/` prefix is correctly in place. The `/` action (lists out all opportunity instances and allows one to add an opportunity instance) should really be at `admin/`.

Reassigning to myself to look into this!

**Comment by MatthewVita** [comment]
Fixed https://github.com/saxifrage/cityasacampus/commit/677cd65eca76a0b2e573dce1b3d12a4dabcba6f0

Closing
