### ISSUE TITLE
consider zenhub.io

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#169]

**Comment by timothyfcook** [comment]
Checked this out today. I'm interested, but it would make it harder to include light-weight contributors, since it wouldn't make sense to add them as Zenhub users for $5/month/person.

**Comment by MatthewVita** [comment]
Zenhub is free for OSS

**Comment by timothyfcook** [comment]
oh nice, their website wasn't obvious about that.

**Comment by MatthewVita** [comment]
yep. if we want to switch, we just have to call out how to signup in the README and the "process" page of our site
