### ISSUE TITLE
implement multi-maps

### ISSUE THREAD

**Issue by chadwhitacre** [saxifrage/learn#175]
We are now [generating multi-maps over in `caac-map`](https://github.com/saxifrage/caac-map/pull/32). We need a PR to copy/paste the latest [`resources.json` and `map.svg`](https://github.com/saxifrage/caac-map/tree/6a490514890d26ec8177a6a0f6e962a1e3cfcb51/output) into [this repo](https://github.com/saxifrage/cityasacampus/tree/gh-pages/map), and update the front-end as necessary.

cc: @timothyfcook @cameronscott137

**Comment by timothyfcook** [comment]
Stoked. I checked in with @cameronscott137 to see if he can join on Friday to update the front-end for multi-maps. We also need to work with him to get the nodes/pathways and menus working.

**Comment by chadwhitacre** [comment]
Done in #177.
