### ISSUE TITLE
Setup staging site

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#189]
staging.learnpgh.org

@justinxreese can we move forward on setting this up asap? 

We have a lot of reasons to get it moving quickly.

**Comment by justinxreese** [comment]
I don't have access to DNS configuration to set up a new URL. The app exists on heroku currently. Do we need to make a staging copy or are we using the copy that is there now as staging?

**Comment by cameronscott137** [comment]
At this point, we can likely just repoint the current copy to staging.learnpgh.org, and replace the root domain with a splash page? @timothyfcook, if you agree, can you create the subdomain? @justinxreese can get you the name of the app to drop into the CNAME.

**Comment by justinxreese** [comment]
It is learnpgh

**Comment by MatthewVita** [comment]
closing in favor of https://github.com/saxifrage/cityasacampus/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22CaaC+Deployment+Epic%22
