### ISSUE TITLE
Implement New Opportunity Instance Layout

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#191]
https://cloud.githubusercontent.com/assets/1823300/9644006/f294f454-5192-11e5-8f13-d07ec2bf11e4.JPG

**Comment by timothyfcook** [comment]
See [Eventbrite](http://www.eventbrite.com/e/global-day-of-coderetreat-2013-pittsburgh-tickets-9376287729) layout for reference/comparison

**Comment by MatthewVita** [comment]
@timothyfcook I started working on these changes in a branch (https://github.com/saxifrage/cityasacampus/commit/ac9a1111cd67960e5f624ce4333b35c59c9034a0)

Here's where I'm at. However, before I move along, I need to let you know that in order to leverage Google Maps, we need to add lat/long coordinates to our opportunity instance model. Are you cool with this? How do you want to handle this from a data-entry standpoint from the admin dashboard? (Searching a google map for the location and clicking on it to get lat/long?)

![dev pittsburgh city as a campus opportunity instances](https://cloud.githubusercontent.com/assets/1715206/10268982/2a18f520-6a97-11e5-87a6-f885a3965167.png)

Thanks.

**Comment by MatthewVita** [comment]
Tim, I just went ahead and push my changes to the master branch (https://github.com/saxifrage/cityasacampus/commit/ac9a1111cd67960e5f624ce4333b35c59c9034a0).

The only thing we need to do to finish this up is to figure out the google map part. Thoughts?

**Comment by timothyfcook** [comment]
Looks like we should be able to use the Google Maps geocoding API to automatically acquire `longitude` and `latitude` coordinates based on the address once it is input by the organizer.

https://developers.google.com/maps/documentation/geocoding/intro?csw=1

**Comment by MatthewVita** [comment]
awesome. I will implement this then!

**Comment by MatthewVita** [comment]
@timothyfcook making awesome progress on this btw. just need to add some error handling and position the map over a bit to the left and we're good!
![asdf](https://cloud.githubusercontent.com/assets/1715206/10409058/eda7760c-6edd-11e5-90e3-107352a93453.PNG)

**Comment by MatthewVita** [comment]
...it's been an interesting problem to solve. Thanks to your link to the geocoder api I was able to convert our "human readable" addresses to lat long and send them to the regular maps API! Using an Angular component, we can drop these anywhere in our app in the following format:

 `<google-map address="myAddressOnScope"></google-map>`

reusability FTW!

**Comment by MatthewVita** [comment]
put in a pull request for Chad to review here: https://github.com/saxifrage/cityasacampus/pull/252

:)

**Comment by MatthewVita** [comment]
![capture](https://cloud.githubusercontent.com/assets/1715206/10412582/253e85ae-6f58-11e5-9f5d-53247c0c0d63.PNG)
