### ISSUE TITLE
EPIC: Build out Admin Area for Demo

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#192]
This epic contains the following user stories:
- https://github.com/saxifrage/cityasacampus/issues/194 (Dashboard Links (Learner Context))
- https://github.com/saxifrage/cityasacampus/issues/195 (Dashboard Links (Organizer Context))
- https://github.com/saxifrage/cityasacampus/issues/196 (Dashboard Registration (Organizer Context))
- https://github.com/saxifrage/cityasacampus/issues/197 (Dashboard Home (Organizer Context))
- https://github.com/saxifrage/cityasacampus/issues/198 (Dashboard Add Opportunity Instance (Organizer Context))
- https://github.com/saxifrage/cityasacampus/issues/201 (Dashboard Create Pathway)

@timothyfcook, @cameronscott137, and @myself to work on this

**Comment by MatthewVita** [comment]
@timothyfcook & @cameronscott137: please review this epic before I start working. I've left out the Anchor role for now, even though we'll definitely want that later.

**Comment by timothyfcook** [comment]
Cool. I think I got to all of them. @cameronscott137 any additional thoughts?

**Comment by MatthewVita** [comment]
@timothyfcook I looked over your comments and I think we're on the same page

**Comment by timothyfcook** [comment]
Excellent!

**Comment by chadwhitacre** [comment]
Does it make sense to use a GitHub Milestone to collect the tickets on this epic?

**Comment by MatthewVita** [comment]
done: https://github.com/saxifrage/cityasacampus/milestones/Admin%20Dashboard%20Epic

**Comment by chadwhitacre** [comment]
:-)

In my experience it can still be useful to have a "meta" ticket as part of a milestone for overarching discussion. YMMV

**Comment by MatthewVita** [comment]
Thanks for your thoughts. I believe discussions for the admin dashboard can happen at the granular story level moving forward but I can definitely see good use cases for your "meta" ticket approach with giant epics or those that aren't fully defined.
