### ISSUE TITLE
Dashboard Links (Learner Context)

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#194]
USER STORY:
As a learner, I wish to click on the “Dashboard” link in my city’s CaaC site so that I can see the data associated with my account

ACCEPTANCE CRITERIA:
- Dashboard Page lists
  - “I’m a Learner” link
  - “I’m an Organizer” link
  - alert fires when “I’m a Learner” link is clicked with content “personal account functionality will be added soon!”

**Comment by timothyfcook** [comment]
Let's go with "For Learners" and "For Organizers"

Copy for alert could be:

"Learner accounts are not yet available. For now, just browse opportunities or explore our map!"

**Comment by MatthewVita** [comment]
done https://github.com/saxifrage/cityasacampus/pull/204

![dashboard-links](https://cloud.githubusercontent.com/assets/1715206/9833755/da4ad580-5971-11e5-89ee-a2e872734c06.PNG)

Don't mind the "Our footer doesn't stick to the bottom" issue... Cameron is taking care of that in https://github.com/saxifrage/cityasacampus/issues/160
