### ISSUE TITLE
Dashboard Links (Organizer Context)

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#195]
USER STORY:
As an organizer, I wish to click on the “Dashboard” link in my city’s CaaC site so that I can access the admin dashboard.

ACCEPTANCE CRITERIA:
- Dashboard Page lists
  - “For Learner” link
  - “For Organizer” link
  - when “I’m an Organizer” link is clicked, user is directed to admin/

**Comment by timothyfcook** [comment]
Let's go with "For Learners" and "For Organizers"

**Comment by MatthewVita** [comment]
For Learners
For Organizers

...and For Your Health!

![a](https://cloud.githubusercontent.com/assets/1715206/9777114/1a77339c-572e-11e5-9e5d-9c972347a27e.jpg)

**Comment by timothyfcook** [comment]
Exactamo!

**Comment by MatthewVita** [comment]
done https://github.com/saxifrage/cityasacampus/pull/204

![dashboard-links](https://cloud.githubusercontent.com/assets/1715206/9833755/da4ad580-5971-11e5-89ee-a2e872734c06.PNG)

Don't mind the "Our footer doesn't stick to the bottom" issue... Cameron is taking care of that in https://github.com/saxifrage/cityasacampus/issues/160
