### ISSUE TITLE
Dashboard Registration (Organizer Context)

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#196]
USER STORY:
As an organizer, I wish to create an account.

ACCEPTANCE CRITERIA
- Allows organizer to specify:
  - email
  - password
  - name
  - description
  - url
  - logo
- Uses nav/theme from “regular” site

**Comment by timothyfcook** [comment]
I swear I created a response for this already. Must have gotten lost in the ether, unsubmitted...

The primary note here is that a single account should be able to take on one or both of the `learner` and `organizer` roles.

By default, someone who signs up through the "For Organizers" link would have an account that was usable for both roles. 

By default, someone who signs up through the "For Learners" link would have an account that was usable for _only_ the `learner` role, but could activate their account for the `organizer` role through their dashboard settings.

---

Whenever someone is creating a new account from the "For Organizers" link, after they create their personal account (with both `organizer` and `learner` roles), they should be prompted to either:
1. Create a new organization
2. Associate themselves with an existing organization via a code, e-mail address, or browse/search (they would have to be approved by the org. admin)

Creating an `organization` in the system is separate than an individual signing up for the `organizer` role.

There might be some verification process at a later point concerning whether or not a person is allowed to create an organization (e.g. is Chad allowed to create the Sprout Fund organization? probably not.)... we'll circle back to this.

**Comment by MatthewVita** [comment]
@timothyfcook,

Does this mean https://github.com/saxifrage/cityasacampus/pull/64 is no long applicable? Are we changing the data model?

**Comment by timothyfcook** [comment]
No, it doesn't conflict.

We have roles: `organizer` and `learner`

and we have identity types: `individual` and `organization`

There are no organization accounts, but individuals can associate themselves with an organization.

I understand it's a bit confusing. The `organizer` could be either an `individual` or an `organization`, individuals can be either `organizer` or `learner` or both.

**Comment by MatthewVita** [comment]
@timothyfcook our current models don't have any reference to learners, individuals, or organizations. All we have are users and organizers.

I'll make stories to add those other models and relationships.

**Comment by MatthewVita** [comment]
...actually, I'm having a hard time justifying the `organization` thing. It doesn't appear to be needed if we just treat `organizers` as the `organization`s. For example, here are the technical stories I'm writing up:

## Set up Learner Users

A `learner` user is just a regular Devise `User` with `associated_organizer` as null

## Set up Organizer Users

An `organizer` user is just a regular Devise `User` with `associated_organizer` referencing an existing `organizer`

...right?

**Comment by timothyfcook** [comment]
That should work as long as we keep this in mind:
- as an individual `organizer` (not associated with a group/organization) I need to be able to create an `organizer` record that references my personal information.

Sorry for any confusion.

**Comment by MatthewVita** [comment]
assigning to @sdanko11, but david and myself are all going to pair on this!

**Comment by sdanko11** [comment]
@MatthewVita have you and David started on this?

**Comment by dmtroyer** [comment]
@sdanko11 I have not.

**Comment by MatthewVita** [comment]
@timothyfcook, @sdanko11, @dmtroyer: okay so this user story is more about the actual registration form and theme. The real work will be with this technical story: https://github.com/saxifrage/cityasacampus/issues/240 (requires changes to our model). Once done, we'll be able to put together the devise form no problem.

Let's hop over there and work together to figure out the best solution.

**Comment by sdanko11** [comment]
Within this sign up form is the `name, description, logo, and url` associated with the `user` or the `organization`, i'm assuming it is the `organization` but I just want to double check.

**Comment by sdanko11** [comment]
@MatthewVita @timothyfcook 

I started to implement the form for the organizer admin, I have it working based on my comments on issue [#240](https://github.com/saxifrage/cityasacampus/issues/240).

Questions: 
- What data do we want to save for a `user`, right now all we are set up to take is `email` and `password`
- Do we want to require any of the data associated with a `organizer` I assume that `name` would be the minimum to actually create a `organizer` record?
