### ISSUE TITLE
Dashboard Home (Organizer Context)

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#197]
USER STORY:
As an authenticated organizer, I wish to see all available actions

ACCEPTANCE CRITERIA:
- link to “Add Opportunity Instance”
- link to “View my Opportunity Instances”
- Uses nav/theme from “regular” site

**Comment by timothyfcook** [comment]
Can be "Create Opportunity" and "Manage Opportunities"

In the workflow for Create Opportunity, they will have the chance to schedule instances. This process could also be done from the "Manage Opportunities" page.

**Comment by dmtroyer** [comment]
@MatthewVita Just to confirm, are we staying in Rails land for this stuff? I see there is already a lot of CRUD type scaffoldingy type work done for managing opportunities, opportunity instances, etc.

**Comment by dmtroyer** [comment]
@MatthewVita mostly a nevermind! I dug a little bit deeper and basically got my answer in the admin dashboard epic.

**Comment by MatthewVita** [comment]
:+1:
