### ISSUE TITLE
Create and Document Heroku Button for New Instances

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#20]
So that Tallahassee (or whoever) can spin up their own version.

**Comment by timothyfcook** [comment]
Put it in the Docs and explain how it works

**Comment by chadwhitacre** [comment]
I minimally put it in [the docs](http://cityascampus.org/about/), didn't explain it yet.

**Comment by timothyfcook** [comment]
Closing this for now, we can revisit a button improvement when it becomes needed.
