### ISSUE TITLE
Project structure and new Back-end Dev

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#200]
Now that Justin is headed off to other things, we should use this moment to assess the project and find a new team member.

Two questions.
1. Do we want to continue using the back-end Ruby framework that Justin put in place? I feel like he didn't do that much work on the RoR side, so would it be easier to transition away from it to something that played better to the strengths of @whit537 @MatthewVita and @cameronscott137 ?
2. If we stick with the current stack, I know a Ruby dev who might be a good fit... but anyone have any other recommendations? We're so close to launching alpha... !

**Comment by cameronscott137** [comment]
I'll defer to y'all on this one, but you're right, Justin didn't do a ton,
but he also didn't need to do a ton. From the rails perspective, its a
straightforward problem to solve, and now that the schema and the forms are
in place, there's not a huge amount of work left to get to an alpha.

Given that, it may not make sense to migrate it to another language prior
to November, but again, will defer to Chad and Matthew.

We've got a rails dev on staff with a healthy interest in Angular, and how
the two languages can and should work together. I'll talk with him today to
assess his bandwidth, but he could be a good fit to get the project
launched and stable through November. At that point, we can reassess and
determine a more long-term approach.

On Wed, Sep 9, 2015 at 9:23 AM, Tim Cook notifications@github.com wrote:

> Now that Justin is headed off to other things, we should use this moment
> to assess the project and find a new team member.
> 
> Two questions.
> 
>    1.
> 
>    Do we want to continue using the back-end Ruby framework that Justin
>    put in place? I feel like he didn't do that much work on the RoR side, so
>    would it be easier to transition away from it to something that played
>    better to the strengths of @whit537 https://github.com/whit537
>    @MatthewVita https://github.com/MatthewVita and @cameronscott137
>    https://github.com/cameronscott137 ?
>    2.
> 
>    If we stick with the current stack, I know a Ruby dev who might be a
>    good fit... but anyone have any other recommendations? We're so close to
>    launching alpha... !
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/cityasacampus/issues/200.

## 

Cameron
(610) 883-7342

**Comment by MatthewVita** [comment]
Here are my thoughts:
- I feel more comfortable with RoR now and think we can and should stick with it. We have a good foundation and can run with it. Our project's client will eventually be 100% Angular and RoR will serve as the API only, which is a very valid setup for our project and RoR will fit that bill nicely. Right now we have a bit of hybrid situation going on and that's okay.
- I would argue that Justin did contribute a good bit. Most notably, he put together a _correctly_ designed database schema and worked with me to get the API endpoints up such that Angular could consume them.
- We should take this opportunity to Tweet about our project and how we're looking for volunteers. It would be wise to reach out to a handful of dev meetups in our area as I'm sure some people would appreciate the opportunity to gain experience. If you guys agree, I'll make an issue and own that effort.
- I feel that @timothyfcook and I failed to address https://github.com/saxifrage/cityasacampus/issues/164. We should make this a top priority. Current roadmap is too granular and we didn't follow it; we need to write up a roadmap that is high level but actually stick with it.
- In re: to @cameronscott137 "now that the schema and the forms are in place, there's not a huge amount of work left to get to an alpha." - there is a reasonably large delta between how the admin area works now and what is expected in https://github.com/saxifrage/cityasacampus/issues/192. Put another way: we actually have a good bit of refactoring and designing ahead.

**Comment by cameronscott137** [comment]
@matthewvita, you're correct, and I owe Justin an apology for earlier
comment. He contributed a great deal of thought and expertise toward laying
the groundwork for a successful project. I was moving quickly this morning,
and spoke out of turn.

On Wed, Sep 9, 2015 at 7:50 PM, Matthew Vita notifications@github.com
wrote:

> Here are my thoughts:
> - I feel more comfortable with RoR now and think we can and should
>   stick with it. We have a good foundation and can run with it. Our project's
>   client will eventually be 100% Angular and RoR will serve as the API only,
>   which is a very valid setup for our project and RoR will fit that bill
>   nicely. Right now we have a bit of hybrid situation going on and that's
>   okay.
> - I would argue that Justin did contribute a good bit. Most notably,
>   he put together a _correctly_ designed database schema and worked with
>   me to get the API endpoints up such that Angular could consume them.
> - We should take this opportunity to Tweet about our project and how
>   we're looking for volunteers. It would be wise to reach out to a handful of
>   dev meetups in our area as I'm sure some people would appreciate the
>   opportunity to gain experience. If you guys agree, I'll make an issue and
>   own that effort.
> - I feel that @timothyfcook https://github.com/timothyfcook and I
>   failed to address #164
>   https://github.com/saxifrage/cityasacampus/issues/164. We should
>   make this a top priority. Current roadmap is too granular; we need to write
>   up a roadmap that is high level but actually stick with it.
> - In re: to @cameronscott137 https://github.com/cameronscott137 "now
>   that the schema and the forms are in place, there's not a huge amount of
>   work left to get to an alpha." - there is a reasonable large delta between
>   how the admin area works now and what is expected in #192
>   https://github.com/saxifrage/cityasacampus/issues/192. In other
>   words, we actually have a good bit of refactoring and designing ahead.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/cityasacampus/issues/200#issuecomment-139075238
> .

## 

Cameron
(610) 883-7342

**Comment by MatthewVita** [comment]
It's k. We're all just sad to see him go :(.

**Comment by timothyfcook** [comment]
Cool, thanks for the discussion all. We'll stick with the current stack and try and bring on some new energy. @cameronscott137 let me know if your team is able to deepen their involvement.
