### ISSUE TITLE
Make thicker alleys on map to match design

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#202]

**Comment by chadwhitacre** [comment]
Where's our screenshot of the design? I thought we addressed this at one point.

**Comment by chadwhitacre** [comment]
Scavenged from https://github.com/saxifrage/caac-map/issues/13: 

![screen shot 2015-07-10 at 5 13 36 pm](https://cloud.githubusercontent.com/assets/134455/8629206/2ce6849c-2727-11e5-99ab-fe808a2a2f61.png)

**Comment by chadwhitacre** [comment]
Current:

![screen shot 2015-09-11 at 8 42 39 am](https://cloud.githubusercontent.com/assets/134455/9815036/195ffc1c-5861-11e5-9993-cbce00c4392f.png)
