### ISSUE TITLE
known tech debt

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#217]

**Comment by timothyfcook** [comment]
Stoked about this ticket. 

Let's be sure to add any appropriate details to the documentation on the gh-pages branch as displayed on http://cityasacampus.org/

**Comment by MatthewVita** [comment]
good point... however, I will create a "tech debt" label and break these out into their own issues. That's a better way of tracking. I just kind of put this together as a mind dump.

**Comment by MatthewVita** [comment]
closing in favor of https://github.com/saxifrage/cityasacampus/labels/Tech%20Debt
