### ISSUE TITLE
URGENT: Bios Needed

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#229]
Can I get each of you @MatthewVita @cameronscott137 @whit537 @sdanko11 @chelseaerdner to provide me with a short 3-5 sentence bio about your skills/experience as they are relevant to this project?

I'm applying for a funding competition to support the future of the work!

DUE TOMORROW BY NOON.

**Comment by chadwhitacre** [comment]
> Chad Whitacre is a programmer with 15 years of professional experience, covering a range of technologies and problem domains. He is active in open-source, particularly the Python community. He has not written a templating language.

S'ok? :-)

**Comment by MatthewVita** [comment]
Matthew Vita is a passionate software engineer from Pittsburgh. He enjoys working with Java, JavaScript, and Python to help open source projects and non-profit organizations in a positive way. His other passions include open education and rabbits.

**Comment by timothyfcook** [comment]
Forgot @dmtroyer on this one too!

**Comment by sdanko11** [comment]
Sorry for getting this in late.

Steve Danko has over 2 years professional experience building scalable web applications, for early stage technology companies.

**Comment by cameronscott137** [comment]
Cameron Scott is a co-founder of Inquiri, a Pittsburgh-based agile
marketing and product shop. Prior to that, he worked as a developer,
designer, and product manager for agencies in Pittsburgh, New York, and San
Francisco.

On Wed, Sep 30, 2015 at 3:07 PM, Steve Danko notifications@github.com
wrote:

> Sorry for getting this in late.
> 
> Steve Danko has over 2 years professional experience building scalable web
> applications, for early stage technology companies.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/cityasacampus/issues/229#issuecomment-144509346
> .

## 

Cameron
(610) 883-7342
