### ISSUE TITLE
theme the docs/contributor site

### ISSUE THREAD

**Issue by chadwhitacre** [saxifrage/learn#24]
Currently it's the underlying Jekyll theme we started with ([Scribble](http://scribble.muan.co/2013/05/06/scribble-the-jekyll-theme/)).

**Comment by timothyfcook** [comment]
- Here's [an example](http://www.homeflow.co.uk/technology/api-documentation-with-github-and-jekyll/) of a documentation site built with Jekyll.
- Here is an existing [docs template](http://bruth.github.io/jekyll-docs-template/) we could use to get started. The [github repo](https://github.com/bruth/jekyll-docs-template/) for it is recent and active.

**Comment by timothyfcook** [comment]
@cameronscott137 unless you have a better option, I like [this](http://bruth.github.io/jekyll-docs-template/) docs template to host our documentation/roadmap, etc. Below is a logo we can use.

![learnpgh_logo](https://cloud.githubusercontent.com/assets/1823300/6789567/a2bee4f8-d177-11e4-8baf-0a74dee08dff.png)

**Comment by chadwhitacre** [comment]
I would like to preserve our first logo for all time, by archiving it here. :-)

![cityascampus](https://cloud.githubusercontent.com/assets/134455/6869717/967681cc-d46c-11e4-9b18-112b47d5df13.jpg)

Thank you. :poodle:

**Comment by timothyfcook** [comment]
Speaking of that, @cameronscott137 let's try to get that Docs site up today so that we don't have to look at Chad's logo anymore :dizzy_face: :facepunch:

**Comment by timothyfcook** [comment]
Let's add a page to archive our Google Hangouts.

**Comment by timothyfcook** [comment]
@cameronscott137 I'll take this one over so you can focus on getting the Explore page, etc. so that @MatthewVita and @justinxreese aren't bottle-necked waiting on design.

**Comment by timothyfcook** [comment]
Finished! `git push origin gh-pages --force` accomplished. We are now live at [cityasacampus.org](http://cityasacampus.org/)
