### ISSUE TITLE
Create Organizer User

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#240]
An `organizer` user is just a regular Devise `User` with `associated_organizer` referencing an existing `organizer`

**Comment by MatthewVita** [comment]
@sdanko11 and @dmtroyer similar to what we'll eventually need to do with https://github.com/saxifrage/cityasacampus/issues/241, an organizer user needs to be supported.

My strategy was to add an `associated_organizer` field to the Devise `User` model (which means user table will have a column referencing the foreign key id of the organizer table).

Are we okay with this? Is there a better way to model this?

**Comment by timothyfcook** [comment]
Makes sense to me after our conversation on #196 a not-null value on `associated_organizer` means that user is an `organizer`

Note:
- Users should be able to have multiple `associated_organizer` in case they want to manage or contribute to multiple organizer identities. Some may teach for two or more different providers.

**Comment by sdanko11** [comment]
@timothyfcook @MatthewVita @dmtroyer Im confused as to what the `organizers` table is doing, what does it represent?  An organization?  As it stands right now the Organizers table has attributes for `name, description, description, url, logo_url, topic_id`.  Could you give me a little more context into what it represents.

If it is the case that a `User` should be able to be associated with one or many `organizers`, we would need to implement a join table between `users` and `organizers` with `user_id`, and `organizer_id` attributes.  If the `associated_organizer_id` is in the `user` table we will not be able to associate `users` with more than one `organizer`.

**Comment by sdanko11** [comment]
```
create_table "organizer_admins", force: :cascade do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "user_id",      null: false
    t.integer  "organizer_id", null: false
  end
```

@MatthewVita @timothyfcook 

Here is the table that I am talking about that gives us the flexibility for a user to be an admin of more than one `organizer`.

**Comment by MatthewVita** [comment]
@timothyfcook's note changes things a bit:

> Note:
> Users should be able to have multiple associated_organizer in case they want to
> manage or contribute to multiple organizer identities. Some may teach for two or 
> more different providers.

We'll going to have to leverage a join table that @sdanko11 is talking about. My only comment is to rename it from "organizer_admins" to "organizer_users" because that makes the relationships a bit more clear.

Do we all agree to move forward with this strategy?

**Comment by sdanko11** [comment]
@MatthewVita I agree.

**Comment by timothyfcook** [comment]
How can I test out the admin functionality so far? I'm getting this when I run the app locally:
![screen shot 2015-10-21 at 5 27 15 pm](https://cloud.githubusercontent.com/assets/1823300/10650730/05f9d8b4-7819-11e5-9c1b-6a2ad009729d.png)

**Comment by dmtroyer** [comment]
@timothyfcook I believe @MatthewVita ran into the same issue https://github.com/saxifrage/cityasacampus/pull/251#issuecomment-148873872, I think he or @sdanko11 have plans to fix it.

**Comment by timothyfcook** [comment]
@dmtroyer can we close this out?
