### ISSUE TITLE
Call out workflows to be demo'ed

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#244]
As a presenter, I wish to demonstrate the following critical workflows to the audience:
- A learner browsing opportunities in the directory and clicking the "Register" link
- An organizer inputting opportunities
- A learner browsing opportunities on the map

**Comment by timothyfcook** [comment]
Probably nice and simple:
1. A learner browsing opportunities in the directory and clicking the "Register" link
2. An organizer inputting opportunities
3. A learner browsing opportunities on the map

**Comment by MatthewVita** [comment]
awesome
