### ISSUE TITLE
Put together realistic seed data

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#245]
As a presenter, I wish to show varied opportunities and topics relevant to our city so that the audience is aware of how our platform organizes these in an amazing way

**Comment by timothyfcook** [comment]
I was thinking about this too. I could work on this. What's the best format to deliver seed data in?

I'll make sure to deliver in in the new format re: @dmtroyer work on #163

**Comment by timothyfcook** [comment]
This group will be interested in seeing seed data related to education and careers that are high-supply in Pittsburgh. They want to use our tool to showcase learning opportunities that can help people level-up skills to get high-supply jobs that aren't being filled.

They have research about 50,000+ jobs in our city that aren't filled due to lack of appropriate talent and education. They are also interested in the aging farmer population and lack of new talent there (average farmer age is ~65).

I could see a few main topics:
- Software
- Fabrication
- Agriculture
- Construction
- Art + Design

**Comment by dmtroyer** [comment]
@timothyfcook I imagine we can work with JSON or a spreadsheet, whichever is easier for you.

**Comment by MatthewVita** [comment]
@timothyfcook do you mind if we pull from the CaaC Map dataset? Seems to be a lot of good data there.

**Comment by MatthewVita** [comment]
@timothyfcook please watch this (unlisted) message video I made so we can start a conversation: https://www.youtube.com/watch?v=YU2A_rCkO5I

**Comment by timothyfcook** [comment]
Will do! Sorry was in SF most of the week for work.

**Comment by timothyfcook** [comment]
@MatthewVita thanks for the helpful video!

I could probably get someone to help out gathering seed data. 

Thanks for the great start! I'll plan on finishing seeds.rb myself or with some help.

Happy to take this one over so you can help finish the Admin dashboard and get our repo published. I'm hoping to show this off during the meeting at 'learnpgh.org'

**Comment by MatthewVita** [comment]
Sounds good.

So I was originally thinking you'd demo the app locally on a projector, but I can try and stand up the app on a temporary server. 

I put together a specific epic for deployment: https://github.com/saxifrage/cityasacampus/milestones/CaaC%20Deployment%20Epic but for now, we'll just get a bare bones version up. I'll try to squeeze this in before the deadline. Otherwise, make sure you have a projector!

**Comment by timothyfcook** [comment]
I'll do it on a projector regardless, just a nice extra touch to type in the URL and let them access it for reference after we leave if they want.

**Comment by MatthewVita** [comment]
okay, cool. see my comment here: https://github.com/saxifrage/cityasacampus/issues/223

I'll do the full epic after this early demo. I'm just going for quick and dirty with this server standup

**Comment by timothyfcook** [comment]
Yeah no worries if it's not live.

**Comment by MatthewVita** [comment]
I'm hoping that tomorrow's standup will provide us with the visibility we need to see if we're actually going to meet the early demo's deadline. I'm a bit nervous...

**Comment by timothyfcook** [comment]
I believe in us! Hopefully we can put in a real solid day on Friday.
