### ISSUE TITLE
Put together slidedeck using Google Presentation

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#246]
As a presenter, I wish to show various CaaC features and workflows in parallel to a presentation so I can give the audience context on the problems CaaC is solving and long term goals.

**Comment by timothyfcook** [comment]
For this, I'll probably grab screenshots from the platform to include in the Deck and then do a live demo after I explain the concept/functionality.

We can use a lot of the value propositions and ideas from the Knight Foundation submission, as well as others I have been writing and working on.

Also I have the initial grant submission (attached)
[learnpgh narrative.pdf]

(https://github.com/saxifrage/cityasacampus/files/10104/learnpgh.narrative.pdf)
