### ISSUE TITLE
Early Demo Epic -> Dependencies

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#248]
list here:
- (consideration) if we have time, maybe we can work more on the dashboard
- (consideration) maybe I can get the home page design mockup into HTML/CSS/JS

**Comment by timothyfcook** [comment]
I'm hoping @cameronscott137 will jump in on the home page implementation.

Something else we could do would be to allude to future non-existing features, like Badges, a recommendation engine, up/down voting, and the ability for students/employers to Suggest new opportunities that don't exist yet.

@cameronscott137 @chelseaerdner maybe we could add a third column to the home page About section #186  called "For Employers" and list some of these features.

**Comment by chelseaerdner** [comment]
@cameronscott137 is at an event today and out of the office. But, I am sure he will be able to get the homepage rolling @timothyfcook. The third column in the about section will be no problem. We can just choose another shade a blue to differentiate it from the other two.

**Comment by MatthewVita** [comment]
@chelseaerdner can you provide a status update on this plz? Thanks.

**Comment by cameronscott137** [comment]
@matthewvita: on this now

On Wed, Oct 14, 2015 at 8:36 PM, Matthew Vita notifications@github.com
wrote:

> @chelseaerdner https://github.com/chelseaerdner can you provide a
> status update on this plz? Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/cityasacampus/issues/248#issuecomment-148241620
> .

## 

Cameron
(610) 883-7342

**Comment by timothyfcook** [comment]
woohoo! Homepage!!!!!! Missing you all from SF.

**Comment by MatthewVita** [comment]
Awesome news. LMK if you need anything.
