### ISSUE TITLE
Implement CaaC HomePage

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#249]
Per @chelseaerdner design in #186 

Also, let's use the "Learn Pgh" language and name when we stand it up (not the City as a Campus name) , since we'll need to be Pittsburgh-centric for the Demo with local funders #248

**Comment by MatthewVita** [comment]
https://github.com/saxifrage/cityasacampus/tree/master/client/app/home is the homepage location. Let me know if there's questions

**Comment by cameronscott137** [comment]
To confirm, we want the city blocks in the background hero image to animate
to full opacity one-by-one? Cycle on an endless loop?

On Thu, Oct 8, 2015 at 7:14 PM, Matthew Vita notifications@github.com
wrote:

> https://github.com/saxifrage/cityasacampus/tree/master/client/app/home is
> the homepage location. Let me know if there's questions
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/cityasacampus/issues/249#issuecomment-146713363
> .

## 

Cameron
(610) 883-7342

**Comment by timothyfcook** [comment]
Sounds great!

**Comment by timothyfcook** [comment]
Whatever beautiful way @chelseaerdner had it

**Comment by timothyfcook** [comment]
@cameronscott137 this is definitely the priority for yinz before Wednesday. if you can, merge what you have so far. I'd like to add any additional Copy, etc.

**Comment by cameronscott137** [comment]
@timothyfcook, its up now in the `bourbon` branch, but it will be more efficient for you to make content changes against Chelsea's PDF and send them over, rather than right in the code.

**Comment by timothyfcook** [comment]
Okay. The primary change for this would be to remove all instances of "City as a Campus" and replace those with "Learn.Pgh"

**Comment by timothyfcook** [comment]
Including the "CAAC" in the menu bar.

**Comment by cameronscott137** [comment]
Done. Sure its already on your radar, but we'll need content for the "About Learn.PGH" section on the home page, too.

**Comment by cameronscott137** [comment]
Home page done here: 2b87068d1ea78b9f3c0c05f71bd22bf68e478fba

Will need one more round of style tweaks, plus your bullet content.

**Comment by timothyfcook** [comment]
Awesome.

@cameronscott137 For the bullets:

Let's go with:

## About Learn Pgh

_One place to find all of the learning in Pittsburgh_

### For Learners:
1. Browse the directory and learning map
2. Find pathways to new careers or interests
3. Start learning, earn badges, and progress towards new opportunities

### For Organizers:
1. Publish your learning opportunities
2. Curate pathways that connect local and digital content
3. Build a comprehensive resource directory for your learning community

**Comment by cameronscott137** [comment]
Fabulous. Will have done in 20 minutes.

On Tue, Oct 27, 2015 at 5:16 PM, Tim Cook notifications@github.com wrote:

> Awesome.
> 
> @cameronscott137 https://github.com/cameronscott137 For the bullets:
> 
> Let's go with:
> 
> About Learn Pgh
> _One place to find all of the learning in Pittsburgh_
> For Learners:
> 1. Browse the directory and learning map
> 2. Find pathways to new careers or interests
> 3. Start learning, earn badges, and progress towards new opportunities
> 
> For Organizers:
> 1. Publish your learning opportunities
> 2. Curate pathways that connect local and digital content
> 3. Build a comprehensive resource directory for your learning community
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/cityasacampus/issues/249#issuecomment-151646466
> .

## 

Cameron
(610) 883-7342

**Comment by timothyfcook** [comment]
@cameronscott137 

For the text in the Hero image at the top:

# Learn.Pgh

_Pursue your passions and unlock new opportunities._

**Comment by cameronscott137** [comment]
All text updated here: c6a2bf0d896998a5c7f28ea5ff4eb4a674a27710

**Comment by timothyfcook** [comment]
awesome. You making a PR to merge the `bourbon` branch with `master` ?

**Comment by cameronscott137** [comment]
@timothyfcook, yes. Making some other refinements, but will have everything merged over by @MatthewVita's 9PM curfew.

Watch the skies for additional updates.

**Comment by timothyfcook** [comment]
:partly_sunny:

**Comment by MatthewVita** [comment]
@cameronscott137 if you need more time, LMK. Otherwise, throw everything into master and :dancer:

**Comment by cameronscott137** [comment]
@matthewvita, should be good to go by 9:10! Will ping you as soon as good.

On Tue, Oct 27, 2015 at 8:46 PM, Matthew Vita notifications@github.com
wrote:

> @cameronscott137 https://github.com/cameronscott137 if you need more
> time, LMK. Otherwise, throw everything into master and [image: :dancer:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/cityasacampus/issues/249#issuecomment-151685418
> .

## 

Cameron
(610) 883-7342

**Comment by cameronscott137** [comment]
@MatthewVita :dancer::dancer::dancer::dancer::dancer::dancer:

**Comment by timothyfcook** [comment]
:dash:
