### ISSUE TITLE
Onboard Matthew and Discuss Stack

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#26]
Let's setup a time for @whit537 @justinxreese and I to gHangout with @matthewvita about our new plans and stack choices. He needs to know what's going on and be able to share out his thoughts on Angular, databases, etc.

Have time this weekend for a few minutes? Or we can hash it out on this thread.

**Comment by MatthewVita** [comment]
I'm free this weekend for a G+ hangout. I'd love to meet with you guys "face to face".

While we figure out a good time for our call... let's talk about our Stack here to get a headstart:

Tim mentioned you guys would like to use a RoR backend. I'm cool with that... I'm more of a Python person but I recently pair-programmed a Ruby script at my job with someone that lives and breathes Ruby (I learned a lot of idioms as a result).

How about we use RoR or Sinatra (put together in an MVC style, using discrete libraries as we need them) for our backend and something like Angular.js or Knockout.js for our frontend? I already scaffold-ed out an angular project on the Sproutfund repo that we can use immediately.

What were you guys thinking about in terms of the DB? Tim and I were using a NoSQL graph db called Neo4j with the other project. I can see us mixing it with a SQL database (MySQL, Postgres, etc).

**Comment by timothyfcook** [comment]
I like the idea of RoR and Angular. Its data-binding is so slick. 

Just sketching out ideas for roles here:

Back-end: RoR (Justin)
Front-end Data-binding to RoR with Angular (Matthew)
Front-end Design/Implementation (Cameron)
Project Design/Management/Documentation/Open-Source (Chad)
Project Lead, Design, Copywriting and Payer-of-Bills (Tim)

**Comment by MatthewVita** [comment]
Tim, I'm fine with my position on that list. I can def help on the backend as well.

I'm guessing we don't need a role for DB person if we're going to use one of those slick Ruby DB ORMs?

**Comment by timothyfcook** [comment]
Obviously, lots of overlap if and when necessary, those just seem to be your main areas of expertise.

**Comment by MatthewVita** [comment]
so I put together this Angular.js Frontend and Sinatra.rb Backend repo for us to consider: https://github.com/saxifrage/cities-as-a-campus

...I'm a big fan of "fractal design" in software where features are broken out in "fractal" feature folders, in case you're wondering why the structure isn't using the traditional "models, controllers, views, libraries, tests, etc" structure.

Thoughts?

...btw, we can bring in tons of ruby Middleware with Sinatra

**Comment by timothyfcook** [comment]
@justinxreese what do you think about the stack and possibly using RoR (or Sinatra) coupled with Angular?

**Comment by MatthewVita** [comment]
(my https://github.com/saxifrage/city-as-campus repo reflects this consideration, btw)

**Comment by justinxreese** [comment]
Need to look at some angular/rails documentation. Will look at this tomorrow more

**Comment by timothyfcook** [comment]
Cool, thanks.

**Comment by MatthewVita** [comment]
@justinxreese let me know if you have questions about Angular along the way!

**Comment by timothyfcook** [comment]
@justinxreese @MatthewVita if yinz have a minute and want to have a chat to figure out what Matthew can help, let's get in the Gitter: https://gitter.im/saxifrage

**Comment by timothyfcook** [comment]
Matthew is on-boarded. Closing this, assuming that you two will chat soon. Letting #33 take over, let's try to put a final decision in there soon.
