### ISSUE TITLE
Create New Roadmap

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#27]
Here was the previous iteration:

**Comment by justinxreese** [comment]
It would be useful to have some good idea of dates and work items per sprint so I can organize this with the work of my other clients

**Comment by timothyfcook** [comment]
Definitely. Hope to work on it this weekend. Will definitely need help from you to identify specific work. Any chance you have a minute to chat with Matthew and I about the tech stack?

**Comment by timothyfcook** [comment]
Need everyone's thoughts and edits here: https://github.com/saxifrage/learn/blob/gh-pages/roadmap.md before we can close this.
