### ISSUE TITLE
Dashboard Upgrade datetime Picker

### ISSUE THREAD

**Issue by dmtroyer** [saxifrage/learn#274]
The current `datetime-local` HTML5 picker is only supported by Chrome. Upgrade to something more broadly supported, including IE9, on the various `DateTime` fields on the Admin Dashboard.

See @MatthewVita's https://github.com/saxifrage/cityasacampus/issues/198#issuecomment-148872488 for more information

**Comment by MatthewVita** [comment]
This will be corrected with the new angular-based dashboard forms
