### ISSUE TITLE
Figure out why codeship is building on pushes to GH pages branch

### ISSUE THREAD

**Issue by justinxreese** [saxifrage/learn#28]

**Comment by justinxreese** [comment]
Contacted codeship support

**Comment by justinxreese** [comment]
Just not possible :(

**Comment by chadwhitacre** [comment]
Discussed on https://www.youtube.com/watch?v=d_1t11KZslc. We can move the GitHub pages site to its own repo if it gets to be a problem to have it as a branch in the same repo.
