### ISSUE TITLE
What Pathway Am I On?

### ISSUE THREAD

**Issue by chadwhitacre** [saxifrage/learn#280]
For https://github.com/saxifrage/cityasacampus/issues/279 I want to report what pathway the bug is on, but I'm not finding this information anywhere in the UI.

**Comment by timothyfcook** [comment]
There's supposed to be a menu but @cameronscott137 turned it off I think?

**Comment by cameronscott137** [comment]
We had a static menu in the upper left, but someone hid it with CSS.
Regardless, unless we're content with the flyout menu covering the
navigation, we will need to re-think placement and structure anyway.

On Mon, Oct 26, 2015 at 9:39 AM, Tim Cook notifications@github.com wrote:

> There's supposed to be a menu but @cameronscott137
> https://github.com/cameronscott137 turned it off I think?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/cityasacampus/issues/280#issuecomment-151135735
> .

## 

Cameron
(610) 883-7342

**Comment by chadwhitacre** [comment]
> but someone hid it with CSS.

I cannot tell a lie: https://github.com/saxifrage/cityasacampus/commit/de6075877a5efed9569ae0af73eeaa5526875eea#diff-7274b05633c2b7471d969b11ddb5f95aR202. :disappointed:

**Comment by timothyfcook** [comment]
Cool. Let's replace the menus. Maybe top-right aligned?

**Comment by cameronscott137** [comment]
That was my thought as well. Probably best to toss the ball back to
@chelseaerdner and have her re-implement the nav here.

On Mon, Oct 26, 2015 at 9:54 AM, Tim Cook notifications@github.com wrote:

> Cool. Let's replace the menus. Maybe top-right aligned?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/cityasacampus/issues/280#issuecomment-151140559
> .

## 

Cameron
(610) 883-7342

**Comment by chadwhitacre** [comment]
Started a PR in #328.

**Comment by chadwhitacre** [comment]
Done in #328.
