### ISSUE TITLE
Tooltip Link Goes Nowhere

### ISSUE THREAD

**Issue by chadwhitacre** [saxifrage/learn#282]
In fact, clicking on the tooltip text causes erratic map behavior.

**Comment by cameronscott137** [comment]
@timothyfcook to confirm, tooltip title should link to external URL?

**Comment by timothyfcook** [comment]
I thought tooltip just loads the card?

**Comment by cameronscott137** [comment]
Great. Currently, when I click popover title, it closes the popover and opens the card. @timothyfcook, good to confirm and close?

**Comment by timothyfcook** [comment]
Cool!

**Comment by chadwhitacre** [comment]
!m @cameronscott137
