### ISSUE TITLE
Entire Tooltip Should Be Clickable

### ISSUE THREAD

**Issue by chadwhitacre** [saxifrage/learn#283]
I can't click on the padding part of the tooltip, nor on the arrow.

**Comment by timothyfcook** [comment]
Check that. This is the annoying one.

**Comment by cameronscott137** [comment]
Fixed here: e0d170ad089b244a730dada64d374b5b47ac2c80

Impossible to do arrow, but whole tooltip is now clickable.

**Comment by chadwhitacre** [comment]
!m @cameronscott137
