### ISSUE TITLE
Explore card layout broken

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#286]
Urgent fix needed before Wednesday @cameronscott137 

![screen shot 2015-10-26 at 3 09 18 pm](https://cloud.githubusercontent.com/assets/1823300/10739571/9582dc0a-7bf3-11e5-8929-77cc66e8ed36.png)

**Comment by MatthewVita** [comment]
@timothyfcook the cards on the app now were styled to meet chelsea's mockups but are definately not what we should move forward with because I just used floats to emulate a grid system as an MVP. Hate to put you on the spot @cameronscott137 , but did you make progress with setting up masonry grid?

**Comment by timothyfcook** [comment]
Got it. I thought Cameron had pushed up masonry already. Would be nice to have that by Wednesday

**Comment by cameronscott137** [comment]
Grid is fixed here: 721f9ad1ee86a6f7ef47a4694986abf5a6a9a7c0

Jumps from three columns down to two at 750px, and then one for > 550px. Each row of cards clears dynamically to avoid broken rows:

![screen shot 2015-10-27 at 3 34 27 pm](https://cloud.githubusercontent.com/assets/2473472/10770221/76c7e04e-7cc0-11e5-8f64-ce544d196c13.png)

**Comment by timothyfcook** [comment]
Awesome. @MatthewVita how do we publish changes live on learnpgh.org ?
