### ISSUE TITLE
change favicon

### ISSUE THREAD

**Issue by chadwhitacre** [saxifrage/learn#29]

**Comment by timothyfcook** [comment]
once @chelseaerdner gives us a favicon we can make this happen.

**Comment by timothyfcook** [comment]
We'll want to add this to cityasacampus.org

**Comment by timothyfcook** [comment]
noooo we need a favicon up on the gh-pages branch of cityascampus.org

**Comment by timothyfcook** [comment]
when we go here we should see favicon: http://cityasacampus.org/ ...also should put it up on the CaaC_Explore App as well

**Comment by timothyfcook** [comment]
Retina quality favicon or else... 32x32 :8ball:

**Comment by timothyfcook** [comment]
Should it be a transparent background? I can't tell how it will look...

**Comment by timothyfcook** [comment]
Maybe it could have the white filled in and a border following the contours rather than the square.

**Comment by cameronscott137** [comment]
Transparent 32x32 favicons up in both repos. Chrome caches favicons like whoa, even in incognito, so to see it, use a different browser to see it. Alternately: http://cityasacampus.org/img/favicon.ico

**Comment by justinxreese** [comment]
This is completed
