### ISSUE TITLE
dynamic image height on cards

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#293]
So images don't repeat and look bad.
@cameronscott137 

![screen shot 2015-10-26 at 4 40 51 pm](https://cloud.githubusercontent.com/assets/1823300/10741882/6575d71c-7c00-11e5-8f1e-79e9739f156c.png)

**Comment by cameronscott137** [comment]
Fixed here: 329b12b12afe27befaf745b78dc6293772008338

The `background-size: cover` rule will proportionally scale the image to occupy the entire <div>. The result, however, can make smaller images appear pixelated. Not disastrous, but any way to adjust the size of images being used prior to the demo?
