### ISSUE TITLE
Neighborhood is too prominent on cards

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#294]
I don't like how the Organization Name is adjacent to the Neighborhood name, sharing the same same font, etc. They look like they are one piece of information. Let's either remove neighborhood name from the cards or find a better place for it.

![screen shot 2015-10-26 at 4 40 51 pm](https://cloud.githubusercontent.com/assets/1823300/10741914/a352e2b4-7c00-11e5-8943-c1c82b432faf.png)

**Comment by cameronscott137** [comment]
Fixed here: 09186aa176c52dccc7bc5fd381bfe907754b6dfe

![screen shot 2015-10-27 at 1 54 36 pm](https://cloud.githubusercontent.com/assets/2473472/10767498/caeaed64-7cb2-11e5-86f8-a8dd9b0ef568.png)
