### ISSUE TITLE
`gulp` not on my PATH?

### ISSUE THREAD

**Issue by chadwhitacre** [saxifrage/learn#296]
The README [sez](https://github.com/saxifrage/cityasacampus/blob/8b652a82157dd1833fc4ae3fcee54bc0fbbd6e67/README.md#application-install) to run:

```
$ gulp
```

I find `gulp` in `client/node_modules/.bin/`, but that's not on my PATH. Why does the README expect it to be and it's not?

cc: @MatthewVita

**Comment by chadwhitacre** [comment]
`rails` is also not on my PATH:

```
$ rails s
```

**Comment by chadwhitacre** [comment]
(`bundle exec rails s` does the trick.)

**Comment by MatthewVita** [comment]
You'll want to install Gulp as a global app:

npm install --global gulp

**Comment by chadwhitacre** [comment]
Ah, I see now:

> This project depends on [...] Gulp [...], please see instructions for your system to get these dependencies installed.

Thanks, @MatthewVita. :)
