### ISSUE TITLE
Cursor Over Card is Text Select Instead of Pointer

### ISSUE THREAD

**Issue by chadwhitacre** [saxifrage/learn#300]
... and yet the cards are clickable!

![screen shot 2015-10-26 at 5 10 42 pm](https://cloud.githubusercontent.com/assets/134455/10742628/82486ab8-7c04-11e5-853a-f0b8637306f4.png)

**Comment by MatthewVita** [comment]
I agree. we should see a pointer. I'm assigning myself but probably won't get to this for the demo. Not a huge deal.

**Comment by cameronscott137** [comment]
This is a CSS fix, I think. I'll get it when I do the styling stuff today.

**Comment by MatthewVita** [comment]
Yep.

Thanks,

Matthew Vita
www.matthewvita.com

**Comment by cameronscott137** [comment]
Fixed here: https://github.com/saxifrage/cityasacampus/commit/e14387883f0282e51e5b639bd92e1f9b085cbc48

Will be merged as part of home page, masonry, etc. later today.
