### ISSUE TITLE
Dashboard Should Know My Dern Role

### ISSUE THREAD

**Issue by chadwhitacre** [saxifrage/learn#302]
When I'm authenticated and I click "Dashboard," I shouldn't be asked whether I'm an organizer or a learner.

![screen shot 2015-10-26 at 5 12 49 pm](https://cloud.githubusercontent.com/assets/134455/10742695/d62a3fc6-7c04-11e5-8d02-e37c8016636f.png)

**Comment by MatthewVita** [comment]
see comment here: https://github.com/saxifrage/cityasacampus/issues/301

**Comment by MatthewVita** [comment]
Will be handled with the introduction of the angular dash
