### ISSUE TITLE
"We Have a Website!" Celebration and Next Steps Meal

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#305]
Scheduled for November 2nd, 6:00 PM at Noodlehead.
Unless anyone has a veto. 

We'll talk over our work so far and next steps now that we have a real website on the internet. We'll also discuss the rousing subject brought up in #285 

Everyone's invited! That means you @sdanko11 @whit537 @chelseaerdner @MatthewVita @dmtroyer 

Food/Drinks/SteamBuns on me.

**Comment by timothyfcook** [comment]
@cameronscott137 is your crew joining us? Sounds like the other 3 folks are in.

**Comment by cameronscott137** [comment]
@timothyfcook We're dahn. See you at six.

**Comment by chadwhitacre** [comment]
!m *

Thanks for dinner, @cameronscott137 (and @timothyfcook :)!

**Comment by chadwhitacre** [comment]
We missed you, @MatthewVita! :-(
