### ISSUE TITLE
Tenant-Specific Configuration

### ISSUE THREAD

**Issue by dmtroyer** [saxifrage/learn#316]
Thinking towards a multi-tenant strategy, there will be a number of fields and text that will need to be configured on a tenant by tenant basis.
- Tenant Name

I imagine there are a number of ways to do this, maybe it could be managed localization style in a yml file or possibly we could do this through the admin dashboard.

**Comment by dmtroyer** [comment]
#285

**Comment by MatthewVita** [comment]
closing dupe of https://github.com/saxifrage/cityasacampus/issues/285
