### ISSUE TITLE
Confirm Weekly Meeting

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#32]
@whit537 @justinxreese @cameronscott137 Per our discussions yesterday, sounds like we are planning on a weekly meeting or Google Hangout to reset our weekly sprints.

How is 10:00 am for everyone?

**Comment by justinxreese** [comment]
I can't do that time this Friday, but that should work normally

**Comment by timothyfcook** [comment]
@justinxreese does a different time this Friday? then we can plan on 10:00 moving forward.

**Comment by justinxreese** [comment]
Actually. 10 works this week. I forgot the start time of something.

**Comment by timothyfcook** [comment]
Let's plan to meet in the chat --https://gitter.im/saxifrage/learn-- a few minutes before 10 and I'll setup a Hangout. 

This will be our plan moving forward. Meet in Gitter for saxifrage/learn at 10 every Friday.

**Comment by zavg** [comment]
Hi guys! Please feel free to check out new service to hold regular online meetups using Google Hangouts on Air: [webmeetups.net](webmeetups.net).

The service automatically reminds about meetup start in a day and in an hour, deals with time zones, allows you to select active participants and watchers if there are more then 10 attending people. You get rid of Hangouts url and Youtube url copy-pasting, it automatically handles all these things. Also it nicely embeds all YouTube videos in your meetup history.

I am service founder and we just came to production, so I warmly invite you to check out our service. Do not hesitate to ask any questions!

**Comment by zavg** [comment]
Hi guys! Please feel free to check out new service to hold regular online meetups using Google Hangouts on Air: [webmeetups.net](webmeetups.net).

The service automatically reminds about meetup start in a day and in an hour, deals with time zones, allows you to select active participants and watchers if there are more then 10 attending people. You get rid of Hangouts url and Youtube url copy-pasting, it automatically handles all these things. Also it nicely embeds all YouTube videos in your meetup history.

I am service founder and we just came to production, so I warmly invite you to check out our service. Do not hesitate to ask any questions!

**Comment by zavg** [comment]
Hi guys! Please feel free to check out new service to hold regular online meetups using Google Hangouts on Air: [webmeetups.net](webmeetups.net).

The service automatically reminds about meetup start in a day and in an hour, deals with time zones, allows you to select active participants and watchers if there are more then 10 attending people. You get rid of Hangouts url and Youtube url copy-pasting, it automatically handles all these things. Also it nicely embeds all YouTube videos in your meetup history.

I am service founder and we just came to production, so I warmly invite you to check out our service. Do not hesitate to ask any questions!

**Comment by zavg** [comment]
Hi guys! Please feel free to check out new service to hold regular online meetups using Google Hangouts on Air: [webmeetups.net](webmeetups.net).

The service automatically reminds about meetup start in a day and in an hour, deals with time zones, allows you to select active participants and watchers if there are more then 10 attending people. You get rid of Hangouts url and Youtube url copy-pasting, it automatically handles all these things. Also it nicely embeds all YouTube videos in your meetup history.

I am service founder and we just came to production, so I warmly invite you to check out our service. Do not hesitate to ask any questions!
