### ISSUE TITLE
Decide on Stack

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#33]
One recommendation on the table is Ruby on Rails with Angular.
@MatthewVita has some Angular skills, @justinxreese has RoR skills. Could be a nice combination.

Of course, we don't have to use Angular and can default to jQuery, etc.. Just wanted to bring up the Angular option again, since it could pair nicely.

Here are some resources:

http://angular-rails.com/
http://www.angularonrails.com/ruby-on-rails-angularjs-single-page-application/
http://blog.honeybadger.io/beginners-guide-to-angular-js-rails/

**Comment by justinxreese** [comment]
Angular on top of rails could be an option to increase the usability of the app, but I don't think it should be done at the start. We should build out some of the core features so that we have a stable base, and then look at replacing some of the interface's interaction with the app with Angular things. Probably can start after Sprint 2

**Comment by MatthewVita** [comment]
I'm fine with that plan, but we should aim to really separate the frontend and the backend when we do make the switch. @justinxreese have you ever used https://github.com/rails-api/rails-api ?

**Comment by justinxreese** [comment]
I haven't

**Comment by MatthewVita** [comment]
Would you be opposed to having our backend being solely the backend piece? AKA an API that clients (Angular, our case) consume?

**Comment by MatthewVita** [comment]
...if not, would rails-api make sense or can we just use Rails without all of the frontend stuff?

**Comment by justinxreese** [comment]
I'd be up for it if it gains us a good bit. Right now, with the lack of any obligation to the Chicago API, I'm not sure it is all that valuable. rails-api probably would make the most sense there. The easy use of Angular templates over top of their API was a benefit originally, but now it seems we're designing to the technology and shouldn't really worry about it until it directly benefits the project.

**Comment by MatthewVita** [comment]
I agree with you.

However, keep in mind that there will probably come a point when we have a feature that requires a more complicated UI and it would make more sense to use a JavaScript library/framework**\* to handle it as opposed to Rails.

**\* I'm not married to Angular, but I do know it well and think it's a wonderful tool. There's also libraries like http://facebook.github.io/react/, http://knockoutjs.com/ that solve a similar problem without much overhead.

**Comment by justinxreese** [comment]
I haven't seen anything yet in terms of UI that really necessitates that. We should make JIT decisions and defer them until they are necessary for the project to continue.

**Comment by MatthewVita** [comment]
Cool. As long as we use the appropriate tools for each job, I'm happy. :+1:

**Comment by justinxreese** [comment]
Sounds good. We will reevaluate later.

**Comment by MatthewVita** [comment]
@timothyfcook with all this said, can I rename this repo to be "City as Campus" and wipe my current "City as Campus" repo? (I'll archive it on my machine because the Angular/Gulp stuff there is solid and can be reused later, if needed). I'm assuming this will break things (links, gh page, gitter, heroku?) so let's plan ahead

**Comment by MatthewVita** [comment]
also, you can close this issue when you reply. We're going to just use Rails for the entire app and pull in a JS data-binding library/framework when a more sophisticated client feature will need it.

**Comment by timothyfcook** [comment]
Awesome. Thanks for hashing this out. Let's leave the repo as "saxifrage/learn" for now until we finalize the name in #36 . Okay, so Angular (or something) maybe down the road... remember that we will likely need to connect our data to the Chicago City of Learning data down the road. Not sure what the ramifications are in terms of our build.

**Comment by MatthewVita** [comment]
We will be able to connect with any API from our Rails backend, no sweat.

**Comment by timothyfcook** [comment]
Cool. The only other thing I was consider was us enabling partner sites to natively embed our Explore functionality (their event feed) within their site... maintaining their nav bar, etc. and not using the CNAME strategy in #15  ...having both options will serve more use cases.

**Comment by MatthewVita** [comment]
or we could just have an API endpoint (JSON) accessible to them so they can wire up the feed however they want, with whatever styling they want. That's another conversation, however.
