### ISSUE TITLE
Clientside Admin Dashboard + RESTful Endpoints

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#342]
"This seems like a good time to consider moving the admin dashboard from the rails app to the angular app. There are certainly costs associated with that move which need to be weighed against the cost of maintaining these separately when they really seem to be converging." - @sdanko11 

Discuss.

**Comment by MatthewVita** [comment]
Here's my weigh-in: I totally agree that the admin dashboard should be clientside and use Rails as a REST API. As you know, there are historical reasons why the Rails side takes care of the dashboard and we didn't care because we were striving to get a demo ready.

You're right. they are clearly converging and we want to have maintainable software.

The main areas of work in order to make this happen:
- scaffolding out the angular directives
- implementing an angular-friendly form-validator for all of the CRUD
- tighten up the way the REST endpoints return validation messages
- implement a token auth strategy between Rails and Angular (perhaps the most work, but I can take a day off of work so @sdanko11 and I can tackle this... there's many ways to go about this) 

There's also the consideration of time. Is now a good time to do this, @timothyfcook ? We'd have to modify the roadmap a bit but getting this out of the way now could save a lot of headaches down the road.

**Comment by dmtroyer** [comment]
I'd be happy to start hacking on this if @timothyfcook gives the go ahead.
Some finer grained issues/user stories would be helpful, however.

Also, is there a particular design pattern(s) we want to reference? Every
angular project I've worked on has done things differently.

**Comment by MatthewVita** [comment]
@dmtroyer good observation... most projects implement an auth strategy differently. I am going to type out a design I am familiar with that I think will be appropriate here: https://github.com/saxifrage/cityasacampus/issues/344
