### ISSUE TITLE
Determine Auth Strategy

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#344]
On the Rails side, we need to refactor the login functionality to check username/password and return a secret token to the client (which is stored in the following example table):

``` sql
CREATE TABLE IF NOT EXISTS Session (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    user_id INT(65) NOT NULL,
    UNIQUE(token)
);
```

This is MySQL I threw together but I'm sure it would be easy to represent this in an ActiveRecord model. The token would need to be a GUID, of course. I don't think we need to worry about expiring the users because there's no real security concerns. If our app ever needed websockets, we could throw the connection string in this table as well!

Also on the backend, we need to intercept each authorized API request to check to see if the headers contain a valid DTO of userId, token, and role.

On the frontend side, we could have something like:

``` javascript
angular.module('caac.authentication.service', [
    'caac.authentication.session.service'
  ])
  .factory('AuthenticationService', ['$http', 'SessionService',
    function($http, SessionService) {
      var login = function(email, password) {
        return $http.post('/api/v1/user/login', {
          email: email,
          password: password
        });
      };

      var logout = function() {
        return $http({
            method: 'POST',
            url: '/api/v1/user/logout',
            headers: SessionService.getSessionObject()
          })
          .finally(function() {
            SessionService.destroySession();
          });
      };

      return {
        login: login,
        logout: logout
      };
    }
  ]);
```

  ...notice that the logout function contains headers of the role, userId, and token that will be checked on the backend. All auth endpoints will expect this information.

  ...here's where we would access/store the session information:

``` javascript
  angular.module('caac.authentication.session.service', [

  ])
  .factory('SessionService', ['$window', '$location', function($window, $location) {
    var key = 'caac-session';

    var establishSession = function(userId, token, role) {
      $window.sessionStorage.setItem(key, JSON.stringify({
        userId: userId,
        token: token,
        role: role
      }));
    };

    var destroySession = function() {
      $window.sessionStorage.removeItem(key);
      $location.path('/');
    };

    var getSessionObject = function() {
      var res = null;
      try {
        res = JSON.parse($window.sessionStorage.getItem(key));
      } catch (e) {
        //rare scenario: the session became malformed so destroy it
        destroySession();
      }

      return res;
    };

    return {
      establishSession: establishSession,
      destroySession: destroySession,
      getSessionObject: getSessionObject
    };
  }]);
```

...here's an example of code using the above services

``` javascript
AuthenticationService.login(self.email, self.password)
  .then(function(res) {
    SessionService.establishSession(res.data.userId, res.data.token, res.data.role);

    if (res.data.role === rolesEnum.LEARNER) {
      $location.path('/dashboard/learner');
    } else if (res.data.role === rolesEnum.ORGANIZER) {
      $location.path('/dashboard/organizer/');
    }
  })
  .catch(function(e) {
    if (e && e.data && e.data.error) {
      alert(e.data.error);
    } else {
      alert('System error. Contact your administrator.');
    }
  });
```

 ...and then in the app.js, we could have a `$rootScope.$on('$routeChangeStart', ...)` that has a map of the routes and the allowed authorization to then inspect the session object to see if the user can be routed.

**Comment by MatthewVita** [comment]
@dmtroyer what do you think? This design will satisfy the minimum needed for our auth. I made a few assumptions with the Rails side so we'll have to figure out how exactly we should approach the token stuff there.

**Comment by dmtroyer** [comment]
@MatthewVita I like it, I think it generally satisfies what we're going for. ActionController even has some [token authentication helpers](http://api.rubyonrails.org/classes/ActionController/HttpAuthentication/Token.html).

**Comment by dmtroyer** [comment]
@MatthewVita I'm also curious if there is an _Angular_ design pattern we're subscribing to that I could do more reading on.

**Comment by MatthewVita** [comment]
@dmtroyer okay cool. First step is to figure out the best token strategy from the Rails side. Let's do some research on that this week.

As for the Angular design patterns/practices I'm using: I'm basically using as many directives to make up the UI as possible (where sensible) and the services/factories are used in the traditional sense. I can be more specific if you like, but I tend to use the patterns/concepts that have worked for me in the past and that I've picked up from blogs by people much smarter than I!

**Comment by dmtroyer** [comment]
I found a couple of gems that integrate with devise:
- [devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth)
- [simple_token_authentication](https://github.com/gonzalo-bulnes/simple_token_authentication)

**Comment by dmtroyer** [comment]
[devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth) seems to play nicely with [ng-token-auth](https://github.com/lynndylanhurley/ng-token-auth) for the angular.js side

**Comment by dmtroyer** [comment]
[devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth) seems promising. It is close to the home-rolled strategy @MatthewVita  proposed https://github.com/saxifrage/cityasacampus/issues/344#issue-115675148 with additional features such as devise integration. I was able to get it up and running without too much trouble for user registration and session management. The next step would be to include that authentication in the api endpoints that will be consumed by the angular-side admin ui.

And to be clear, some api endpoints will not have any authentication (at least for now), as they need to be publicly accessible to non-authenticated users. I'm thinking `opportunity_instances#index` for example.

**Comment by MatthewVita** [comment]
devise_token_auth and ng-token-auth it is. This issue was just to identify the strategy so I'm going to close it and make an implementation issue now.

**Comment by MatthewVita** [comment]
https://github.com/saxifrage/cityasacampus/issues/347

**Comment by MatthewVita** [comment]
@whit537: this may be useful for you to review so you can understand where @dmtroyer and I wanted to start with the angular dashboard.

**Comment by chadwhitacre** [comment]
Thanks @MatthewVita, will do! :-)
