### ISSUE TITLE
Invite OSS Contributors

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#35]
Once the project matures more, want to invite more people to help on this.

**Comment by timothyfcook** [comment]
Note from our first weekly call: try and build a more diverse team.

**Comment by justinxreese** [comment]
Did this happen?

**Comment by timothyfcook** [comment]
Waiting to pursue this until we have our apps reconciled and the explore page finished. That will provide a good foundation for people to build on.

**Comment by MatthewVita** [comment]
I had 2 people interested in helping, but neither really came through :(. I can hit them up once more soon, however.

I think we should ask for help after we get opps and explore features done
