### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#37]
@justinxreese I'm trying to get install instructions for local development spelled out on the `README.md`... so far I have Linux but could use a hand on Mac since I don't use Mac (and, yes, I'm assuming you use a Mac since you're a ruby person C: )

I can add in the Windows instructions too.

https://github.com/saxifrage/learn/commit/033963bdb2506f08cee2c90dcf0fac26c0e3b0bc

**Comment by timothyfcook** [comment]
Have Mac, just need Windows. Did we lose the Linux install instructions or are those the same? Will assign this to @MatthewVita now

**Comment by justinxreese** [comment]
I nixed instructions to install dependent services and simply listed them. It's not really on us to prescribe how to install postgres. That information should come from the official postgres documentation. Save that, our application installs and runs the same in all environments.

**Comment by chadwhitacre** [comment]
I think we're all up and running now, ya?

**Comment by MatthewVita** [comment]
@whit537 yep, the install instructions work. @timothyfcook most Windows people use http://www.mingw.org/ so the *nix instructions work (well, as long as the user has the programs installed/configured like Justin mentioned)

:)
