### ISSUE TITLE
Leverage Storage over Cookies for ngToken

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#370]

**Comment by MatthewVita** [comment]
in PR here: https://github.com/saxifrage/cityasacampus/commit/e6cb103f4c97a1bcf2bba1a51287ddfba5d60c2f

**Comment by MatthewVita** [comment]
Still want to find out why library isn't `sessionStorage`. I'm going to try swapping out `localStorage` for `sessionStorage` and see what happens. Will then get in touch with the library authors with findings

**Comment by MatthewVita** [comment]
findings: `sessionStorage` definitely works. Going to pull down the vanilla project and create a PR for discussion with the library authors.

**Comment by MatthewVita** [comment]
PR is here: https://github.com/lynndylanhurley/ng-token-auth/pull/240 :)

**Comment by dmtroyer** [comment]
> Still want to find out why library isn't sessionStorage

If I had to guess, I would say because they want the ability to control Token expiration beyond just one browser session. I believe the default is seven days on the rails gem.

**Comment by MatthewVita** [comment]
https://github.com/lynndylanhurley/ng-token-auth/issues/244

**Comment by MatthewVita** [comment]
^ that is the issue that I will work on in my spare time. We will use localStorage since I'm finding it makes more sense for our use case. closing

**Comment by MatthewVita** [comment]
:+1: for learning new things by experimentation and research!
