### ISSUE TITLE
Implement Dashboard Auth Route Check

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#372]
In `index.js` `run(...)` block, inject our `AuthService` and listen on `$routeChangeStart` to see if route contains "_dashboard_". If so, invoke `AuthService.isAuthenticated()` to ensure user can be routed.

popular design here: http://stackoverflow.com/a/20971528 (ours is going to be much simpler b/c we can assume 'dashboard' routes are the only ones that need whitelisted)

**Comment by MatthewVita** [comment]
@dmtroyer, @whit537 before I start a PR, are you guys cool with this design? There a few other ways to do it (hacking `ng-route` to accept an `authenticatedRoute` boolean property in a granular way, for example).

**Comment by dmtroyer** [comment]
This works for me. I recall reading about a more granular method using angular-ui-router, as well.

**Comment by chadwhitacre** [comment]
Works for me.

**Comment by MatthewVita** [comment]
PR here: https://github.com/saxifrage/cityasacampus/pull/381/commits
