### ISSUE TITLE
Pull request flow

### ISSUE THREAD

**Issue by justinxreese** [saxifrage/learn#39]
I think that even if we merge our pull requests ourselves immediately, we should use pull requests for all changes and never push directly to master. This will make sure nothing bad gets in to master because it'll pass CI.

I'll add everyone here as a contributor on the Codeship team.

**Comment by MatthewVita** [comment]
That's fine with me! Although, documentation changes can probably be merged in directly if we all can agree on that.

Do we want to do code reviews? (It's not possible to "assign" PRs in Github AFAIK but we can just @mention the person to do a review.)

...once we decide on this, we can add a concise "Contribution Guide" in the wiki :)
