### ISSUE TITLE
Bootstrap Rails Application

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#4]

**Comment by chadwhitacre** [comment]
https://afternoon-inlet-4548.herokuapp.com/ :dancer:

**Comment by justinxreese** [comment]
Good to go!

**Comment by timothyfcook** [comment]
woot! step one.

![screen shot 2015-03-20 at 1 49 17 pm](https://cloud.githubusercontent.com/assets/1823300/6757509/00445198-cf08-11e4-9a42-eb61f67d1e0a.png)
