### ISSUE TITLE
Issues issue

### ISSUE THREAD

**Issue by justinxreese** [saxifrage/learn#48]
I'm wondering if there is a better place for these things that seem to be an "eventually" type issue that aren't related to the project state right now. It's getting to be really noisy and going to cause a loss of signal on things that are actionable.

Labeled this meta. Is there a meta-meta?

**Comment by justinxreese** [comment]
Demonstrated by the fact that this is issue #48 on our 5 day old project :scream_cat:

**Comment by timothyfcook** [comment]
haha, great point. Sorry, just started thinking about some important items I didn't want to forget. I'll sequester future-issue-type-things to the Roadmap from now on.

**Comment by timothyfcook** [comment]
Just got really excited about linked data.

**Comment by justinxreese** [comment]
And although sparked by your items, it's still a general question at large. Maybe the roadmap should be included in the README?

**Comment by timothyfcook** [comment]
Right now it's here: http://cityasacampus.org/roadmap/

There is a link to that main page in the readme.

**Comment by justinxreese** [comment]
Ah, missed that. That seems good.

**Comment by MatthewVita** [comment]
Actually, I see the issues as backlog items so I say keep them coming but know that the sprints are sprints and are not allowed to incur scope creep!

**Comment by justinxreese** [comment]
Yeah... but I get an email for each one.....

**Comment by MatthewVita** [comment]
lol, true...

**Comment by timothyfcook** [comment]
After some consideration, I think it makes more sense to use Github issues to keep _all_ issues for the project, even far-off ones. @justinxreese maybe setup an e-mail filter? (chad did this) When using Github issues to see what work to do, just use the filters to narrow your view to the current Sprint or specific tags.

**Comment by timothyfcook** [comment]
Can also edit notifications settings: https://github.com/settings/notifications
