### ISSUE TITLE
Revise Data Model to Reflect JSON-LD Sketch

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#50]
Building on the work of #16

**Comment by timothyfcook** [comment]
https://github.com/saxifrage/learn/blob/master/examples/opportunity_instance_linked_data.json

**Comment by timothyfcook** [comment]
@justinxreese also add: a `short_description` (limited to 160 characters) and `event_logo` per #51

**Comment by justinxreese** [comment]
Going to use this tomorrow https://github.com/rails-api/active_model_serializers

**Comment by justinxreese** [comment]
@timothyfcook I don't understand why an opportunity instance has multiple "meeting times". Isn't that the purpose of the opportunity instance?

**Comment by justinxreese** [comment]
Got a lot of the way there. Need info to continue.

**Comment by timothyfcook** [comment]
Cool. Here's an example to explain your question:
- Picture a 4-part beginner coding workshop that is a recurring offering from Code and Supply. Students sign up for all four sessions at once. They need to know when the meetings times for those four sessions. All four sessions, taken in total, are a single `opportunity_instance` of the "Beginner Coding Workshop Series" `opportunity` and each instance has 4 meeting times.

Make sense?

Need anything else?

**Comment by justinxreese** [comment]
To me, those sound like opportunities and opportunity instances. There are 4 opportunities and N opportunity instance for each

**Comment by timothyfcook** [comment]
1. `opportunity` - "Beginner Coding Workshop Series" --- sort of a template for ALL Beginner Coding Workshops that will ever happen
2. `opportunity_instance` - "Beginner Coding Workshop Series: Summer, 2015" --- an instance of the four-week workshop series.
3. `meeting_time` - "Beginner Coding Workshop Series: Summer, 2015 - Second Meeting, 7/18/2015" --- The second meeting time for the four-part series happening this summer.

Some `opportunity_instance` have multiple meeting times. Some don't. Some will just meet one time.

Some `opportunity'` will only have a single instance.

The three levels of data should allow for flexibility for all types of opportunities, regardless of complexity.

Did I convince you yet?

**Comment by justinxreese** [comment]
I think more often than not, that'll add overhead to an organizer's workflow. What if instead, `Opportunity` instances where clone-able?

**Comment by justinxreese** [comment]
Note, I don't mean `OpportunityInstance` instances.... :scream_cat:

**Comment by timothyfcook** [comment]
haha, I had to catch myself on that as well. Yeah, that's similar to how the City of Learning people do it. Their `opportunity` is just a clone-able template for `opportunity_instance`...

Ok, that will work. So maybe we don't need `opportunity_instance` ? Just use `opportunity` and have `meeting_time`s ... ?

`meeting_time` just being time/dates of each meeting for that `opportunity`

**Comment by justinxreese** [comment]
Yeah. Right now, `OpportunityInstance` objects act similar to how you've described `MeetingTimes`. Should we rename `OpportunityInstance` to `MeetingTimes`?

**Comment by timothyfcook** [comment]
Sounds good. That wasn't how I envisioned `opportunityInstance` I think `MeetingTimes` makes more sense.

**Comment by timothyfcook** [comment]
Assuming that change, I'm going to close this as mark it "good enough" for now.
