### ISSUE TITLE
spike out subdomain routing

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#53]
To understand risks/details for CNAME pages for Organizations, etc. Relates to #21

**Comment by chadwhitacre** [comment]
https://www.google.com/search?q=rails+subdomain+routing

http://asciicasts.com/episodes/221-subdomains-in-rails-3
http://guides.rubyonrails.org/routing.html
http://stackoverflow.com/questions/21536986/rails-routes-url-and-subdomains
http://www.raysrashmi.com/2014/07/23/rails-routes-constraints
http://richonrails.com/articles/basic-subdomains-in-ruby-on-rails
https://gist.github.com/bsodmike/1369419

**Comment by justinxreese** [comment]
This is a dupe of #15

**Comment by chadwhitacre** [comment]
Thanks.
