### ISSUE TITLE
Add Category data-type to Organizer object

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#55]
So that we can list affiliated Organizers on the Topic/Category pages. (e.g. on the "Design & Making" page listing Assemble as an affiliated Organizer")

**Comment by timothyfcook** [comment]
@justinxreese is this done?

**Comment by justinxreese** [comment]
Is not. This will be the same topics used to organize events?

**Comment by timothyfcook** [comment]
Correct. We wanted to be able to associate organizers as well.

**Comment by justinxreese** [comment]
Added with #115
