### ISSUE TITLE
Decide on fixed list of Topics/Categories

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#56]

**Comment by MatthewVita** [comment]
If this is seed data, then we already have a small conversation going on about that here: https://github.com/saxifrage/learn/issues/30 :)

What are the high-level topics that we know have courses in PGH?

**Comment by timothyfcook** [comment]
Here's what we can start with:
- Robotics
- Design & Making
- Coding & Gaming
- Media-Making
- Food & Gardening
- Storytelling
- Civic Engagement
- Art and Performance
- Energy & Environment

**Comment by timothyfcook** [comment]
Long-term, we'll have to figure out how to do this. I'm not sure if we should always seed the Topics list (and limit it to a particular set) or open it up to tagging by the community and create the Major Topics list based on the topics that have the most tagged pieces of content.

**Comment by MatthewVita** [comment]
seeding !== limiting the topics to a particular set

The users would always be able to add more later
