### ISSUE TITLE
Deploy to heroku with CI

### ISSUE THREAD

**Issue by justinxreese** [saxifrage/learn#6]
Codeship already setup. Need heroku config.

**Comment by chadwhitacre** [comment]
Right now [it's](https://afternoon-inlet-4548.herokuapp.com/) under my personal account. We should move to a Saxifrage org at Heroku.

**Comment by chadwhitacre** [comment]
Waiting for new Heroku account from @timothyfcook in order to transfer app over there. API key is scoped to user.

**Comment by justinxreese** [comment]
Good to go!
