### ISSUE TITLE
Age Segmenting Issue

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#60]
Something I've been struggling with is how to segment different age groups. Options:
1. Create separate sites (one for youth, one for adults) --- this doesn't deal nicely with the fringe cases. What about 17 year olds who could utilize resources from both?
2. Have data-driven age segmentation within a single site by automatically filtering content based on the logged-in users age range. --- this could be tricky to implement and doesn't work for logged in users (unless we get all site visitors to share age before they browse).

Thoughts? 

This is an open question that will be important down the road. I'm not sure what is best, or what the other options are.

**Comment by justinxreese** [comment]
Age groups as in people that are allowed or people that are interested?

**Comment by MatthewVita** [comment]
This is a big deal. I think we should list out our options and vote on it:

1) show all courses/resources for all ages
2) show age-range specific courses/resources as based on the auth'd user's age, if non-auth'd user, show all courses/resources for all ages
3) show age-range specific courses/resources as based on the auth'd user's age, if non-auth'd user, show a modal asking for age range (persists to session)
4) split up the platform into age-range specific sites

My vote is for option 3.

**Comment by justinxreese** [comment]
I think organizations will make the call on this. They will most often only hold events for one age range. Or if they're like the library, where they're hosting multiple age groups, probably want them all to be listed on the same platform.

**Comment by MatthewVita** [comment]
@justinxreese right, the organizers can choose the age ranges but it's the colliding of irrelevant event topics I believe we're talking about. For example, "Jean-Paul Sartre: A Survey", "Gender, Sexuality, and the Body in Islam", and "Basic Reading Skills" could all show up in one place.

(Clearly the philosophy course and the sexuality course are more adult-oriented and the reading course is more youth-oriented.)

**Comment by justinxreese** [comment]
That'll be a problem at any scope I think. When you get down to a level, there will always be a segmentation of the group. "Basic Reading Skills" certainly is significantly different than "Basic Art Skills". All event based things struggle with this, but we should look at some of the leaders that have come up with displaying `SELECT *` in creative ways:

https://www.eventbrite.com/
http://www.ticketmaster.com/
http://www.showclix.com/

Eventbrite - I get a collection of things around Pittsburgh across a variety of categories and then a list of categories that I can drill into

Ticketmaster - seems to be based on my previous log ins and they're tracking me in some way - local stuff, sports, music, what's popular overall

Showclix - choose things that highlight their partnerships with impressive organizations to convince people to use their platform

**Comment by MatthewVita** [comment]
good points.

How do you feel about something like option 2 then? `If (user.isAuth && isNum(user.age))`, query with a `WHERE`, otherwise no `WHERE`.

**Comment by timothyfcook** [comment]
Eventbrite/Ticketmaster/Showclix are not the best example per se, since they none of them are really seeing Youth as a primary user. We have two very different primary users: youth and adults.
If I am 13 years old and I go to the Explore page it's really confusing/unhelpful to be browsing options, 70% of which I probably should not attend. Vice versa for the adult case.

I'm for option 3 as well. Although, maybe with a fairly passive modal that one could ignore if they wanted.
Sort of an option between 2 and 3.

If we have all Organizations assign an `ageRange` for the `opportunity` then the controller could fetch _only_ objects that have an `ageRange` that matches the `user.age`

**Comment by MatthewVita** [comment]
I'm thinking option 2 is the best for an MVP and option 3 is the long term option.

I like what you're saying about the `opportunity` presenting the range :+1:

**Comment by MatthewVita** [comment]
We implemented the range as optional fields upon creating the instance. Closing.
