### ISSUE TITLE
Build Client-Side Models w AngularJS

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#63]
For 3rd party organizations API. It seems like we could get started on this sooner than later. Although we tabled this in the conversation in #33 it might not hurt to get this going so that we don't have to re-implement it later on.

**Comment by timothyfcook** [comment]
From @MatthewVita -- For the Explore Page/explore page embed:

ToDo List:
1. search validation
2.add media queries
3. add another \* endpoint in test data
4. clean up deps
5. add better (smaller) images in test data
6. cleanup code
7. more/better datatypes in test data
8.lazy loading
9.put jquery feed in `/etc`
10. write up README
11. push to github

**Comment by MatthewVita** [comment]
can we close this because of https://github.com/saxifrage/learn/issues/65 ?
