### ISSUE TITLE
Reference API endpoints from JS

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#65]
Angular?

**Comment by timothyfcook** [comment]
.json files already exist: http://learnpgh.herokuapp.com/opportunities/1/.json new data fields are being updated by @justinxreese

**Comment by MatthewVita** [comment]
I'm already working on this with the Explore page (which will be full blown Angular with our app and jQuery based for the small embedded feed)

**Comment by MatthewVita** [comment]
...or am I missing the point of this issue?

**Comment by MatthewVita** [comment]
please see https://github.com/saxifrage/CaaC_Explore

@whit537 I believe Tim asked you to talk with me about this issue (from the hangout).

@timothyfcook thanks for recording the hangouts, btw. Really helps me stay in the loop!

**Comment by timothyfcook** [comment]
Cool, yeah, sorry. Some of the issues may be redundant. Feel free to remove some or fold them together. Basically the hope for this week is:
- Justin gets the DB squared away and serves up JSON
- You wrap it up in Angular and work with Cameron to put it into his nice new design.
- Cameron finishes the design with Chelsea and we have a working/attractive Explore page to look at by Friday!

**Comment by MatthewVita** [comment]
can't promise the filtering/lazy loading by end of week... I've got the stomach flu :(

**Comment by timothyfcook** [comment]
Ouch. No worries. I'm sick also : (

**Comment by MatthewVita** [comment]
closing b/c this is going to be taken care of with https://github.com/saxifrage/learn/issues/105
