### ISSUE TITLE
Create Platform Variables File

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#66]
We should have one file where we can change ALL of the major variables to enable easy "white-label" customization. We started on this here: https://github.com/EntelekiaLearning/Website/issues/9

This time we should add some .css attributes (e.g. color scheme, etc.)

**Comment by MatthewVita** [comment]
https://github.com/saxifrage/CaaC_Explore/blob/master/app/shared/conf/ConfService.js

**Comment by MatthewVita** [comment]
Let me know about CSS attributes as they come up, but this config service should do the trick for our frontend stuff.

Also, a lot of front-end people like to use Sass/LESS/Stylus/etc variables for global styles (e.x.: `$NAV_COLOR = #2B1B17`)... @cameronscott137, what's your preference?
