### ISSUE TITLE
rake db:setup fail

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#69]
`Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"utf8", "database"=>"learn_test", "pool"=>5, "host"=>"localhost"}
-- enable_extension("plpgsql")
rake aborted!
PG::ConnectionBad: could not connect to server: Connection refused
    Is the server running on host "localhost" (127.0.0.1) and accepting
    TCP/IP connections on port 5432?
could not connect to server: Connection refused
    Is the server running on host "localhost" (::1) and accepting
    TCP/IP connections on port 5432?
could not connect to server: Connection refused
    Is the server running on host "localhost" (fe80::1) and accepting
    TCP/IP connections on port 5432?`

Thoughts?

With:
`ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin11.4.2]`
`gem -v 2.0.3`
`rails -v 4.2.1`

**Comment by MatthewVita** [comment]
Tim,

Is the Postgres service running? Please run `$ netstat -na` and check to
see if port `:5432` is in there.

Thanks,

Matthew Vita
www.matthewvita.com

**Comment by timothyfcook** [comment]
No port 5432. How do I make sure I'm accepting TCP/IP connections on that port?

**Comment by MatthewVita** [comment]
Tim,

Postgres probably isn't running... how'd you install it? Brew?

I'm a Linux/Windows guy so I won't be able to help you get the service
running on a Mac (don't know the conventions there), but that's what you'll
need to do :)

Thanks,

Matthew Vita
www.matthewvita.com

**Comment by cameronscott137** [comment]
Tim: If it's simpler, I can help you get up and  running tomorrow morning first thing. It can be kind of a tricky thing to troubleshoot remotely.    

---Sent from Boxer | http://getboxer.com

On April 2, 2015 at 2:20:08 PM EDT, Matthew Vita notifications@github.com wrote:Tim,  Postgres probably isn't running... how'd you install it? Brew?  I'm a Linux/Windows guy so I won't be able to help you get the service running on a Mac (don't know the conventions there), but that's what you'll need to do :)  Thanks,  Matthew Vita www.matthewvita.com  On Thu, Apr 2, 2015 at 1:28 PM Tim Cook notifications@github.com wrote:  > No port 5432. How do I make sure I'm accepting TCP/IP connections on that > port? > > — > Reply to this email directly or view it on GitHub > https://github.com/saxifrage/learn/issues/69#issuecomment-88981090. > —Reply to this email directly or view it on GitHub.

**Comment by timothyfcook** [comment]
Yeah looks like psql is not running. I did use brew. 

Noob alert.

**Comment by timothyfcook** [comment]
Thanks Cameron!

**Comment by chadwhitacre** [comment]
Another option: http://postgresapp.com/.

**Comment by justinxreese** [comment]
We could use something like https://github.com/ddollar/foreman to ensure dependent services are running to start the app. Not sure it's worth it right now with just postgres. Next service we add, I'll add foreman

**Comment by timothyfcook** [comment]
Yeah, I was looking at that... but I didn't see a homebrew install option.

Aw, it's a cute elephant!

....and, victory!
![screen shot 2015-04-03 at 9 20 49 am](https://cloud.githubusercontent.com/assets/1823300/6982664/d5936b38-d9e2-11e4-939e-0be67a376018.png)

**Comment by justinxreese** [comment]
But yeah. That's definitely the reason. Just start postgres

`pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start`

edit: posted at the same time as the comment above. disregardable
