### ISSUE TITLE
Start Style Guide in Docs Site

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#80]
For Chelsea.

If you don't want to clone the repo using Github you can just very simply edit the markdown file in the browser here: https://github.com/saxifrage/learn/blob/gh-pages/_posts/2015-04-01-branding.md

**Comment by timothyfcook** [comment]
@chelseaerdner now that you are getting closer on the brand, think about codifying the style guide and resources on this page. It'd be nice, for instance, to provide a full file set of the logos (.svg, .eps, .png, etc.) in color, grey, black, and white. In a range of useful sizes (favicon to full-size).

**Comment by chelseaerdner** [comment]
@timothyfcook great, no problem. I am going to make some final revs to the logo, just to clean and tighten it up a bit, then will start to package the assets in a useful way.

**Comment by chelseaerdner** [comment]
@cameronscott137 briefly shared the first rev of the brand guide with @timothyfcook yesterday but I figured I would document it here for all to see. 

Below is a brand guide that would live on http://cityasacampus.org/doc/branding.html. The purpose of the guide is to educate users that are interested in CaaC on the appropriate colors and usage for the CaaC brand. This page will also give people the opportunity to download high res logos and brand assets for outside marketing usage. 

Please note that there is some lorem ipsum on the page. I hope to fill that space with a mission statement for CaaC along with 3 main value props that highlight what matters most to us. The navigation you see living on the left side of the layout serves as a way help users easily navigate down the page incase they are looking for a specific thing. As they click on different elements in the side navigation, the page will anchor to that section. 

As always, I will filter any feedback into further revisions. 

Thanks!

![caac_brandguide_04222015_icons copy](https://cloud.githubusercontent.com/assets/11842603/7322235/ca175178-ea74-11e4-877a-c9d847e5bdd5.png)

**Comment by timothyfcook** [comment]
@chelseaerdner this looks great! Next steps would be to get it into the documentation site. That lives on the [gh-pages](https://github.com/saxifrage/learn/tree/gh-pages) branch. Specifically in this file: https://github.com/saxifrage/learn/blob/gh-pages/_posts/2015-04-01-branding.md

Go ahead and edit the Markdown and add in all of the appropriate assets ...let me or @cameronscott137 know if you need help.

You could also change out the old logo for ours and update the fonts and site colors to match the style guide.

**Comment by timothyfcook** [comment]
Be sure to include files for all 4 logo types, as well as white and grayscale... a link to the font assets would also be helpful. Basically everything someone would need to replicate the style guide somewhere.

**Comment by timothyfcook** [comment]
@chelseaerdner do you need any help implementing this? I want to get it up on the documentation site here: http://cityasacampus.org/doc/branding.html

**Comment by chelseaerdner** [comment]
@timothyfcook this is on my list to get up and out this week. I should be good to go but I will let you know if I run into any issues, thank you!

**Comment by timothyfcook** [comment]
I got this mostly up and running. Had to reformat the html so it worked okay in a Markdown `.md` file and then had to move images and code into the seed files for the site. The way the Jekyll sites work is that they have build files that get rendered by the Jekyll engine into the actual site. The `_site` folder should never be edit, but rather the file/folders that get built into `_site`.

Sorry, it's a bit non-intuitive if you've never used it before.

Check it out here: http://cityasacampus.org/doc/branding.html

Looks like we might be missing some fonts, etc.?

**Comment by timothyfcook** [comment]
Also looks like maybe some of the styles aren't applying?

**Comment by timothyfcook** [comment]
@chelseaerdner could you look at this and make any tweaks necessary to get it looking like your initial layout?

I am pulling the html in via an "Includes" using Jekyll, so the actual page is found in the `_includes` folder: https://github.com/saxifrage/learn/blob/gh-pages/_includes/branding.html

**Comment by MatthewVita** [comment]
Looks like @cameronscott137 did great work on implementing this. We should make another user story to create the text... or do we already have that?

**Comment by timothyfcook** [comment]
This is probably good for now.

**Comment by MatthewVita** [comment]
cool. I added a story to our backlog for when we do get to adding content: https://github.com/saxifrage/learn/issues/157
