### ISSUE TITLE
heroku

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#81]
uh oh https://news.ycombinator.com/item?id=9315144

...should we move to Digital Ocean?

**Comment by justinxreese** [comment]
No. We should pay $7. The amount of overhead on any other setup is not worth $7 (DO doesn't have a free plan, lowest is $5/month, so it's not worth $2).

**Comment by timothyfcook** [comment]
Cool. Let me know if and when we need to upgrade.

**Comment by MatthewVita** [comment]
oh, my bad. I didn't see that it was only $7/month >.<

Thanks,

Matthew Vita
www.matthewvita.com
