### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#86]
We need to support things like `opportunities/{{searchTerm}}.json` for the explore feature

**Comment by timothyfcook** [comment]
Hmmm makes sense. @justinxreese thoughts? ...you could at least display all opportunities for now?

**Comment by timothyfcook** [comment]
Or filter opportunities by topic?

**Comment by MatthewVita** [comment]
for example, this is what I'm doing with my silly test data server https://github.com/saxifrage/CaaC_Explore/blob/master/data-server/server.js#L61

**Comment by justinxreese** [comment]
added an endpoint `opportunity_instances/topic/<topic name>.json` to filter opportunities by topic. Will add full text search in #107
