### ISSUE TITLE
Evening Session

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#87]
@MatthewVita can you, @cameronscott137, and myself do some hacking some evening this week? I'll buy dinner. Can do any night. ....maybe @justinxreese can join via video.

Now that #51 is just about done I'd like to get it up and running asap so we have something to look at and build from. Would especially love to sort out the Angular/Rails integration once and for all. But the foremost goal is to have a working and beautiful explore page that uses the Rails API data.

**Comment by MatthewVita** [comment]
will definitely be able to schedule this in... I'll share my availability once I update my schedule :)

**Comment by timothyfcook** [comment]
Excellent!

**Comment by MatthewVita** [comment]
...would Wednesday work? 4pm?

**Comment by timothyfcook** [comment]
Works great for me. @cameronscott137 ?

**Comment by cameronscott137** [comment]
I'm onsite in Oakland all day until right around four. Will try and hustle
out of there ASAP, but as long as you're cool with the potential for a 4:15
start, that works for me, too. Look forward to meeting you, Matthew!

On Tue, Apr 14, 2015 at 9:47 AM, Tim Cook notifications@github.com wrote:

> Works great for me. @cameronscott137 https://github.com/cameronscott137
> ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/learn/issues/87#issuecomment-92854035.

## 

Cameron
(610) 883-7342

**Comment by timothyfcook** [comment]
Sounds great. Let's meet here at the Sprout Fund! I'll procure dinner for us.

**Comment by MatthewVita** [comment]
@cameronscott137 looking forward to meeting you as well.

...how about 4:30 just to be safe?

**Comment by cameronscott137** [comment]
It's like you already know me ;)  4:30 sounds good.

On Tue, Apr 14, 2015 at 4:12 PM, Matthew Vita notifications@github.com
wrote:

> @cameronscott137 https://github.com/cameronscott137 looking forward to
> meeting you as well.
> 
> ...how about 4:30 just to be safe?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/learn/issues/87#issuecomment-93046357.

## 

Cameron
(610) 883-7342

**Comment by MatthewVita** [comment]
![](http://media.giphy.com/media/oYK11dXjrkXh6/giphy.gif)
