### ISSUE TITLE
Client Side Tasks

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#89]
@timothyfcook  @cameronscott137 it was nice working with you today! I feel that we laid down some foundations, agreed on overall approaches, and made good progress.
## Next steps are:
- [x] Matthew/Cameron to translate Jade to HTML and Stylus to SCSS **
- [ ] Matthew/Cameron to build up Cameron's beautiful SCSS http://www.codeshare.io/y8LpJ into the client ***
- [ ] Matthew/Cameron to build up Cameron's beautiful HTML http://www.codeshare.io/keFea into the client ***
- [x] Matthew/Tim to build up better mock data and bind it to Angular (we'll eventually rid of the test data server in favor of our actual RoR API, ofc)

*\* reasoning is that the terseness of Jade and Stylus is awkward for non-technical users, so let's use the right tools for the job!

**\* Unfortunately, we can't just say I'll do one task in a branch and you do the other... we'll have to work together at the same time on these! I just got hit with an email from TurboTax saying that one of my returns was rejected so I don't know if I'll get started on these tonight like I planned :C.

![](http://media.giphy.com/media/rjibxsFWbKQ8/giphy.gif)

**Comment by MatthewVita** [comment]
...btw, make sure you all rerun `npm i` now that we have changed gulp's deps a bit :)

**Comment by MatthewVita** [comment]
...bam! https://github.com/saxifrage/CaaC_Explore/commit/a6c672993b28d92f2c55ba332d053cda403969a0

**Comment by timothyfcook** [comment]
hooray! did those taxes work out?

I see a shiny salmon-colored nav bar and the login/out buttons. Progress!

**Comment by MatthewVita** [comment]
taxes are done... something was wrong with an address I entered or something.

...the nav bar is all I focused on. Now that we've switched to HTML/SCSS, you can help out if you have time since you know HTML/CSS. Make sure to commit/push early and often since we're all working on the same files in the codebase.

**Comment by MatthewVita** [comment]
@cameronscott137 where's that logo asset, btw?

**Comment by MatthewVita** [comment]
``` html
  <div ng-repeat="o in opportunities" class="card">
    <img src="{{o.img}}"/>
    <h5 class="name">{{o.name}}</h5>
    <p class="date">{{o.date | date:'MM.dd.yyyy'}}</p>
    <div class="sub">
      <p class="organizer">{{o.organizer_name}}</p>
      <p class="loc">{{o.location}}</p>
    </div>
    <div class="desc">{{o.short_description | truncate: 80: '...'}}</div>
    <div class="type" ng-if="o.price">Event type: Non-free ({{o.price | currency:'$'}})</div>
    <div class="type" ng-if="!o.price">Event type: free</div>
  </div>
```

bindings and filters are in place for explore cards!

@cameronscott137 I didn't do any of the CSS for the cards so it's really ugly at the moment

@timothyfcook is that how you wanted the logic for the event type to be?

**Comment by MatthewVita** [comment]
https://github.com/saxifrage/CaaC_Explore/commit/ca4a4474626db1ddaee98c681f0cd3b7004556e2

**Comment by MatthewVita** [comment]
closing b/c these are broken out as individual tickets.
