### ISSUE TITLE
start doc site using gh-pages

### ISSUE THREAD

**Issue by chadwhitacre** [saxifrage/learn#9]

**Comment by timothyfcook** [comment]
Set up a homepage with navigation tree and "edit these docs" links at the bottom of each page.

**Comment by chadwhitacre** [comment]
I'll see if I can get the basics in place.

**Comment by chadwhitacre** [comment]
`gh-pages` branch kicked off in https://github.com/saxifrage/learn/commit/1ac58778bde524e3f2ec9d85d8b65f0b57a21019.

**Comment by chadwhitacre** [comment]
I just turned off GitHub's Wiki feature for this repo, since we're planning to use GitHub pages for documentation instead.

**Comment by chadwhitacre** [comment]
http://saxifrage.github.io/learn/

**Comment by timothyfcook** [comment]
Set it up with http://prose.io/

**Comment by chadwhitacre** [comment]
Started! :-)

http://cityascampus.org/

Will reticket next steps ...
