### ISSUE TITLE
Layout: Individual Opportunity Page

### ISSUE THREAD

**Issue by chelseaerdner** [saxifrage/learn#90]
I am excited to hear that most of us are on board with the third option for the CaaC logo mark. After hearing that, I started to extend that across the individual opportunities page that @cameronscott137 shared with everyone is yesterday's meeting. 

You see two different headers in the layouts below to represent the option for either a logo or full width image on the explore page. If the user were to select a logo to present on the explore page, their opportunities page would look similar to the first layout. If the user were to select a full width image, it would look like the second. 

Please review some of the layout choices, as I am sure that we will need to move some things around on the page for hierarchy sake. 

Looking forward to hearing thoughts.

Thanks!

![caac_opportunity_04162015-01](https://cloud.githubusercontent.com/assets/11842603/7190534/ee7706ba-e454-11e4-8d6e-ec35ab51b8d9.png)

![caac_opportunity_04162015-02](https://cloud.githubusercontent.com/assets/11842603/7190535/ee7c4940-e454-11e4-94af-49c5bfaa9e46.png)

**Comment by MatthewVita** [comment]
beautiful.

@timothyfcook @cameronscott137 I forgot what we decided yesterday, but how are we going to handle the opportunities that don't have many `Event Details`... do we:

0) implement validation such that all data must be entered
1) the event details box height will be proportional to what data is available
2) the event details box height will have a `min-height` that is the sum of the 4 boxes on the left, regardless of data availability

**Comment by timothyfcook** [comment]
We could require certain fields on event entry form and design from there.

**Comment by MatthewVita** [comment]
so, require enough fields to fill the event details box height to at least the sum of the 4 boxes (including y-axis container margin) on the left?

**Comment by cameronscott137** [comment]
I'd recommend we simply hide Event Detail rows that don't have values.

Having two columns at different heights doesn't bother me so much. Plus,
the left column's height will vary, too, depending on the presence of
badges, organizational info, etc. Unless we force heights via CSS on both
columns—which is def. not a responsive best practice—it'll be impossible to
ensure on every page.

In terms of validation, I would recommend:
- Event Name
- Event Date
- Venue
- Address
- Description

Adding much more to that could become burdensome for smaller events.
Thoughts?

On Thu, Apr 16, 2015 at 5:15 PM, Matthew Vita notifications@github.com
wrote:

> so, require enough fields to fill the event details box height to at least
> the sum of the 4 boxes (including y-axis margin in the box container) on
> the left?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/learn/issues/90#issuecomment-93841223.

## 

Cameron
(610) 883-7342

**Comment by MatthewVita** [comment]
that makes the most sense in terms of responsiveness, so let's do that.

**Comment by cameronscott137** [comment]
Cool. @MatthewVita, if you have time, do you have enough to begin building out the bones of an individual opportunity page? I just need a spot to code into for now. Can go back over and drop variables in after the fact.

**Comment by MatthewVita** [comment]
I'd like to get the explore page design implemented first. I'll be freed up a bit tomorrow and a good part of the day of sunday

**Comment by timothyfcook** [comment]
This looks great. Was it intentional to remove the search bar from the nav on these pages, or it just didn't make it into these mockups?

**Comment by chelseaerdner** [comment]
@timothyfcook it was not necessarily on purpose. It falls under the issue of hierarchy I wanted to discuss for each layout. I removed the search bar simply because I was looking at the opportunity pages as more supplementary pages. Figuring that once the user has reached an opportunity page, they'd already gone through the search process. Although, having the search bar consistently live up in the nav is probably beneficial to the user in the long run. I can update the spec, if you agree.

**Comment by timothyfcook** [comment]
Might make sense to have it persist. Easier to code if the nav is identical across all pages. Unless there's a powerful design motive to eliminate it on certain pages.

**Comment by MatthewVita** [comment]
we're coding by component, so it's simple as "plugging in":

``` html
<navbar search="false"></navbar>
```

on pages as we see fit :)

(just let me know)

EDIT: I forgot to include the attribute that we can implement with ease.

**Comment by timothyfcook** [comment]
I like having the default background image being the textured logo-esque blocks. The Organizer could override it by uploading their own image for an Opportunity.

**Comment by chelseaerdner** [comment]
I updated the spec to reflect a consistent search function in the nav.

![caac_opportunity_04162015-01](https://cloud.githubusercontent.com/assets/11842603/7230696/3617b064-e73e-11e4-987d-a8618ff4ca97.png)

![caac_opportunity_04162015-02](https://cloud.githubusercontent.com/assets/11842603/7230697/3619beae-e73e-11e4-99bf-b666e0d52dcf.png)

**Comment by MatthewVita** [comment]
...speaking of the search bar, can I get the search icon as an svg?

**Comment by cameronscott137** [comment]
@MatthewVita Have assets all saved out for you. Can you advise on your preferred way to store and link to assets in Angular? Been looking around, but can't find any comps to your fractal approach so far.

**Comment by MatthewVita** [comment]
awesome! And wherever makes sense... for example, putting explore assets in `./explore/` and navbar/search assets in `./shared/navbar/`

**Comment by timothyfcook** [comment]
woo! we have assets!

**Comment by cameronscott137** [comment]
@MatthewVita Thanks. How would I link to said assets in an html file? Is there a function I can call to return a root URL? Images in question are in "app/shared/navbar/images/asset_name.svg"

**Comment by cameronscott137** [comment]
@MatthewVita Same q for linking to assets in SCSS? eg) background-image: url('./images/asset_name.svg');

**Comment by MatthewVita** [comment]
@cameronscott137  https://github.com/saxifrage/CaaC_Explore/commit/eb463b81bb0f63b4e49eb4d431387f5a0691183f

**Comment by MatthewVita** [comment]
^ there's an example for you of how to work with assets (adds a gh fork image to homepage via SCSS and HTML) :+1: 

Note: please do a `pull` from `master` to get the latest gulp that deals with assets.
