### ISSUE TITLE
Build Opportunity Page

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#91]
I've started here https://github.com/saxifrage/CaaC_Explore/commit/369afc4865e18ea20bfef092a16df6b33283e554

...which loads the following silliness when an explore card is clicked (it talks to a new test data server endpoint that handles opportunity events by UID):

![eve](https://cloud.githubusercontent.com/assets/1715206/7335662/f520bbb6-eb9b-11e4-8515-5222beec3fbe.PNG)

@timothyfcook @cameronscott137 do we have HTML/SCSS along with the image mockup from @chelseaerdner ? I can start on the bindings regardless, I'm just seeing if I can pretty this up a bit from the get-go.

Thanks.

look here for mockups: https://github.com/saxifrage/learn/issues/90

**Comment by MatthewVita** [comment]
![dev pittsburgh city as a campus opportunities](https://cloud.githubusercontent.com/assets/1715206/7383206/3f5deeac-ede9-11e4-8452-806b62c8ece2.png)

@cameronscott137 and @chelseaerdner:

@timothyfcook and I put this skeleton together to get some of the Angular bindings and routes in place (we also discovered new fields that need to be added to our data model). Sorry for the ugliness, but the HTML and CSS classes should be reusable/a good start to work from. It's a start.

**Comment by timothyfcook** [comment]
@MatthewVita needs to finish working on the data-binding before this is finished.

**Comment by MatthewVita** [comment]
@timothyfcook I added in the bindings and test data to match that of RoR's payload. However, we're really far off from this: https://cloud.githubusercontent.com/assets/11842603/7230697/3619beae-e73e-11e4-99bf-b666e0d52dcf.png

in terms of data,  we currently don't have "Point of Contact", "Neighborhood", "Long Description", "Address" (for the opportunity_instance, not the addr of the organizer), "Website" (for the opportunity_instance, not the url of the organizer), "Badges", or "Attendees".

3 questions:

0) My code is checking for min_age and max_age and then is showing the range. Should I handle cases where there is only one age given? (i.e.: min_age == 14 and max_age == null, so simply show "14")

1) As for the img at the top... it's easier to just show the circular logo of the opportunity for everything for the MVP. We can implement the banner stuff later.

2) Do we have HTML/CSS for this page yet? (no pressure)

**Comment by timothyfcook** [comment]
@justinxreese can we get the rest of that data into the model?
1. we should due some validation on the age range fields to ensure that both min and max are entered.
2. sounds good. @cameronscott137 can put in a nice styling layer that auto-crops the image into a circle
3. Sorry. I stole @cameronscott137 away to help with pgh-dev.cityoflearning.me ...we have to launch it for the summer and were hitting up against deadlines. Hopefully in a week or two he'll be freed up and back on track.

**Comment by justinxreese** [comment]
Badges and attendees aren't due up for a while. I can update the other fields, although it would be much easier if that was updated in the learn repo and I could replace the bogus values myself. cc @MatthewVita

**Comment by justinxreese** [comment]
Actually, based on the ticket name of #106 that's kind of what we already agreed to do. Can we get the latest code in the learn codebase and have all updates in there going forward?

**Comment by MatthewVita** [comment]
if I understand what you're asking, we already have the latest code in learn's `client` branch.

**Comment by justinxreese** [comment]
It doesn't look like this commit https://github.com/saxifrage/CaaC_Explore/commit/400b1a3add58d595314b82d0266a39a5ecf35991 is in `client`

**Comment by justinxreese** [comment]
Oh sorry, I misread the diff

**Comment by MatthewVita** [comment]
most of that is test data

**Comment by MatthewVita** [comment]
you're good!

**Comment by MatthewVita** [comment]
btw, @justinxreese, this function is what you'll be most interested in for the opportunity page: https://github.com/saxifrage/learn/blob/client/client/app/opportunities/OpportunitiesService.js#L17-21

**Comment by justinxreese** [comment]
thanks. is it currently configured to connect to what's running on localhost 3000?

**Comment by MatthewVita** [comment]
https://github.com/saxifrage/learn/blob/client/client/app/shared/conf/ConfService.js#L28 yup

**Comment by MatthewVita** [comment]
https://github.com/saxifrage/learn/issues/114
