### ISSUE TITLE
Style Explore Cards

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#93]

**Comment by MatthewVita** [comment]
can't wait for this!

**Comment by timothyfcook** [comment]
@cameronscott137 need any help on this? Maybe we can have it ready when Matthew rejoins us.

**Comment by MatthewVita** [comment]
@cameronscott137 let's pair up on this. Do you want to meet up on Sunday in the AM via Google Hangouts? I promise I'll be on fast internet this time...

**Comment by cameronscott137** [comment]
@MatthewVita Unfortunately, I'll be traveling this weekend, but thank you for the offer. I dug back in today, and plan to continue on Monday morning. Will ping you with any questions/issues I run into along the way.

**Comment by MatthewVita** [comment]
@cameronscott137 Sounds good.

**Comment by MatthewVita** [comment]
@cameronscott137 just pinging you on this b/c I want to get this story across the finish line soon. Do we have mockups for the cards? If so, I can try my best to replicate it via HTML/CSS. This will free you up for other tasks

**Comment by timothyfcook** [comment]
I feel like we had mock-ups a while back. If not, we could use a similar design to what @chelseaerdner made for http://cityasacampus.org/map/

**Comment by MatthewVita** [comment]
I'd be glad to move forward with Chelsea's design. However, I will leave out the blue button and just allow anywhere within a card to be clickable (takes you to opportunity instance page)

**Comment by MatthewVita** [comment]
@timothyfcook:

Some issues I ran into:
- a lot of data that is on the cards for the map is on our individual opportunity instances page... maybe we can keep the explore cards really concise
- we don't have difficulty
- organization information has a link but our cards can be clicked anywhere to navigate

I just pushed this to master:

![dev pittsburgh city as a campus explore](https://cloud.githubusercontent.com/assets/1715206/9027670/582249cc-392c-11e5-8bb5-03766c01ea92.png)

Obviously price and date need new icons, but what are your thoughts?

**Comment by MatthewVita** [comment]
also of note: I truncated the description with '...'

**Comment by timothyfcook** [comment]
Looks good to me. Some notes:
- We are removing the word "activity" from the Local/Digital item
- We can include some data validation on the admin dashboard via #136 so that the descriptions stay short enough for the design. This is why I was considering a `short_description` as well as a `description` before.

@cameronscott137 @chelseaerdner does this match the original design? I feel like Chelsea had created something at one point.

**Comment by timothyfcook** [comment]
Per #161 let's add duration and difficulty to the cards. @chelseaerdner can you pick an icon for `duration` ? What icon library are we using?

**Comment by chelseaerdner** [comment]
![screen shot 2015-08-03 at 2 15 03 pm](https://cloud.githubusercontent.com/assets/11842603/9044357/1dbac908-39ea-11e5-9f7d-e6c5c51ef6e0.png)
![screen shot 2015-08-03 at 2 14 54 pm](https://cloud.githubusercontent.com/assets/11842603/9044356/1db625e2-39ea-11e5-80c3-841f33283128.png)

The original cards for CaaC were a little different from the resource map ones that we have been working with. Title are pulled from the image and placed beneath and the images are full color for these ones. So, we will not need the dark overlay.

**Comment by chelseaerdner** [comment]
@timothyfcook as far as an icon library I usually download existing ones and tweak them to match the style I am working in. If we make a list of ones we need, I can compile them so we have them in one place. But for now, I will pull an icon for duration.

**Comment by chelseaerdner** [comment]
Attached is an .svg for duration!

*Chelsea Erdner*
Designer
412.310.4697 *m*
chelseaerdner *Skype*
inquiri.com


*Inquiri*M-TH: 8a-6p
F: 8a-4p

**Comment by timothyfcook** [comment]
Nice. Let's go with this layout, but with the 3 icons across the bottom in place of the badges:

Local/Digital    |     Duration     |      Price

**Comment by timothyfcook** [comment]
@chelseaerdner sorry, I don't think you can attach files via e-mail. You'll have to upload it to this issue page on Github: https://github.com/saxifrage/learn/issues/93

**Comment by chelseaerdner** [comment]
Grr. Okay, will do!

**Comment by chelseaerdner** [comment]
Doesn't seem to support .svg's so I just emailed the file to @timothyfcook and @MatthewVita. Let me know if you receive it.

**Comment by MatthewVita** [comment]
Thanks. I'll implement the cards in this way.

**Comment by cameronscott137** [comment]
@MatthewVita You want me to jump in here this week and handle masonry/responsive? Are are you going to trim strings so that each card stays the same height?

**Comment by timothyfcook** [comment]
I like the somewhat variable card height... could be based on the size of the associated image?

**Comment by MatthewVita** [comment]
@cameronscott137 I can definitely use the help. Masonry is robust and cool, but I'd be just as fine with a simple responsive grid system as well. I can trim strings as we see fit but @timothyfcook brings up a good point. Thoughts?

**Comment by MatthewVita** [comment]
@chelseaerdner @timothyfcook I pushed the following HTML/CSS to `master`:

![capture](https://cloud.githubusercontent.com/assets/1715206/9156330/4534c600-3ea4-11e5-8004-5a03c6ddf5e8.PNG)

**Comment by timothyfcook** [comment]
Looking good! @chelseaerdner feel free to offer any design suggestions as well for the final implementation.

**Comment by chelseaerdner** [comment]
These are looking good! There are a couple minor things I would recommend just to clean up spacing a bit. 
- Shrink up the size of the organization and location. The primary focus should first be on the resource name on the card. 
- It looks like we are using a couple different typefaces on the card. We probably need to reduce down to only two, if not one. I think the spec uses Effra all through with varying font weights. If we can't get access to Effra, we will just have to choose the next one that looks good. Open to any thoughts here. 
- Can you add about 20-30px of space about the title and below the icons? Just to open up space on the card a little bit. 
- This may be the screenshot but the blue and green look a little muted on the screen shot. I provided the hex values for the blue and green if you need them. <b>Blue: #0099FF Green: #33CC00</b>

Other than that, I think these are great. @MatthewVita I emailed you an updated .svg for duration. I will get one for price over to you in just a little.

**Comment by MatthewVita** [comment]
Cool, I'll put these on my todo list! Thanks for the followup.

**Comment by MatthewVita** [comment]
To close off this story:
- [x] shrink up the size of the organization and location
- [x] use 1 font (closest webfont to `Effra`, that is)
- [x] add `25px` of space above the title and below the icons
- [x] switch the blue color to `#0099FF` and the green color to `#33CC00`
- [x] implement updated svg for `duration`
- [ ] implement update svg for $

**Comment by MatthewVita** [comment]
![capture](https://cloud.githubusercontent.com/assets/1715206/9241406/23ebc864-4141-11e5-9904-25704b6260d5.PNG)

**Comment by MatthewVita** [comment]
I think the duration svg looks off? Also, please send me a $ svg when you get a chance

**Comment by timothyfcook** [comment]
Looking good. Let's have @cameronscott137 do any final clean-ups or improvements and close this.

**Comment by cameronscott137** [comment]
@MatthewVita Can you recommend the best place within `/client/` to install a third-party js library?

https://github.com/desandro/masonry

There's an option to install via npm, which strikes me as preferable, but happy to do whatever you think is best.

**Comment by MatthewVita** [comment]
@cameronscott137  npm and here you go! https://github.com/saxifrage/cityasacampus/pull/221
