### ISSUE TITLE
Help Cameron Put Files into Angular Structure

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#94]

**Comment by MatthewVita** [comment]
@cameronscott137 we have two options:

1) you can put together the HTML/CSS/images in however you want and just ping me as soon as you push and I'll just change it up as we go
2) I'll make a `cameron` folder with a very traditional folder structure (`pages/`, `styles/`, `images/`, etc) with a gulp script to wire everything together and just ping me as soon as you push and I'll just migrate it over to the Angular convention as we go

...which would be best?

:smiley_cat:

**Comment by timothyfcook** [comment]
@cameronscott137 let him know and we can move forward with it.

**Comment by MatthewVita** [comment]
Closing this out. Plz HMU if questions arise :+1:
