### ISSUE TITLE
Update API to match CaaC_Explore App

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#96]

**Comment by timothyfcook** [comment]
Do this by having it match my example: https://github.com/saxifrage/learn/blob/master/examples/opportunity_instance_linked_data.json

**Comment by MatthewVita** [comment]
note that the two "types" are "logo" and "banner": https://github.com/saxifrage/learn/blob/master/examples/opportunity_instance_linked_data.json#L11

(these relate to the opportunity page)

**Comment by timothyfcook** [comment]
@justinxreese is going to do a back and forth with @MatthewVita on this

**Comment by justinxreese** [comment]
Going to work with @MatthewVita on #106 to refine this, but considering this issue closed
